/* ═══════════════════════════════════════════════════════════
   ARTICLES — ENGLISH VERSION — config/articles.en.js
   Same structure as config/articles.js, keyed by slug. Sections and FAQ
   entries MUST stay in the same order and number as the French source
   (the router and the links are shared). Prices, durations and package
   contents come from the site catalogue: keep them in sync.
   ═══════════════════════════════════════════════════════════ */
const ARTICLES_EN = {
  'combien-coute-une-seance-photo': {
    title: 'BUNKAIO ⊹ | How much does a photo session cost? Rates and factors',
    description: 'Length, location, number of retouched photos, usage rights: what drives the price of a photo session, with our actual rates.',
    h1: 'How much does a photo session cost?',
    excerpt: 'What makes the price of a portrait session vary, our actual rates, and the questions to ask when comparing two quotes.',
    summary: ['The price depends mainly on session length, location, the number of retouched photos and usage rights.', 'At BUNKAIO, a portrait session starts at €290 and goes up to €1,390.', 'Compare two quotes on the same criteria: length, retouched photos, delivery time, rights, travel.', 'The online quote gives you an estimate in 2 minutes, with a personalised reply within 48 hours.'],
    sections: [
      { h: 'What makes the price of a photo session vary', html: '<ul><li><strong>Length</strong>: one hour of shooting does not cost the same as a half-day or a full day.</li><li><strong>Location</strong>: outdoors or in the studio, number of different locations, travel costs.</li><li><strong>Number of retouched photos</strong> delivered: retouching takes significant working time after the session.</li><li><strong>Number of outfits or moods</strong> planned.</li><li><strong>Art direction</strong>: guidance on poses, style and preparation.</li><li><strong>Usage rights</strong>: personal or commercial use, and for how long.</li><li><strong>Delivery time</strong>.</li></ul>' },
      { h: 'Our portrait session rates at BUNKAIO', html: '<p>Our <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">individual photo sessions</a> offer four packages, net prices, no VAT to add (VAT not applicable):</p><ul><li><strong>Starter, €290</strong>: 1-hour session, 8 retouched HD photos, guided selection, delivery in 5 working days.</li><li><strong>Signature, €490</strong>: 2-hour session, 15 retouched HD photos, posing guidance, delivery in 7 working days.</li><li><strong>Premium, €790</strong>: half-day, up to 2 moods, 25 retouched HD photos, 2 outfits, delivery in 7 working days.</li><li><strong>Bunkaio editorial, €1,390</strong>: full day, 4 locations and 4 outfits, 30 retouched HD photos, a short film, delivery in 10 working days.</li></ul><p>All packages include a private download gallery. The studio option, as an alternative to outdoors, costs an extra €80 on the Starter package.</p>' },
      { h: 'Individual or professional session: what changes', html: '<p>A session for yourself, your partner or your family focuses on connection and naturalness. A professional project (brand, company, products) also needs a brief, precise formats and commercial usage rights. Our <a href="/services/photo-produits-packshots/" data-nav="service:commercial">Commercial & products</a> and <a href="/services/photographe-mode-mannequins/" data-nav="service:mode">Fashion</a> services meet these needs, with their own rates.</p>' },
      { h: 'Questions to ask when comparing two quotes', html: '<ul><li>How long is the <strong>session</strong>?</li><li>How many <strong>retouched</strong> photos are delivered, and in what resolution?</li><li>What is the <strong>delivery time</strong>?</li><li>Which <strong>usage rights</strong> are transferred (commercial use, duration)?</li><li>Are there <strong>travel costs</strong>?</li><li>What are the <strong>payment and cancellation terms</strong>?</li></ul>' },
      { h: 'Payment and cancellation at BUNKAIO', html: '<p>A 30% deposit is paid when you order (quote signature) and the balance on delivery. You can pay by bank card or in 3 interest-free instalments with Klarna. Once the quote is validated, the deposit is retained by BUNKAIO if you cancel. More details in the <a href="/faq/" data-nav="faq">FAQ</a>.</p>' },
      { h: 'Get an accurate estimate', html: '<p>The easiest way is our <a href="/devis/" data-nav="quiz">online quote</a>: in 2 minutes you choose your category, package and options, and you receive a personalised reply within 48 hours, with no commitment.</p>' }
    ],
    faq: [
      { q: 'Is the studio an extra cost?', a: 'On the Starter package, the session takes place outdoors or in the studio, with an extra €80 for the studio.' },
      { q: 'Can I pay in instalments?', a: 'Yes: bank card or 3 interest-free instalments with Klarna.' },
      { q: 'Can the photos be used commercially?', a: 'Yes: commercial usage rights are transferred to you with no time limit.' }
    ]
  },
  'preparer-seance-photo-portrait': {
    title: 'BUNKAIO ⊹ | Preparing your portrait photo session: the complete guide',
    description: 'Choosing the location, outfit and light, and getting ready: practical advice for a natural, stress-free portrait photo session.',
    h1: 'Preparing your portrait photo session: the complete guide',
    excerpt: 'Location, outfit, preparation, the big day: everything you need to know for a natural, successful portrait session.',
    summary: ['Define how your photos will be used before choosing the style and the location.', 'Pick comfortable outfits that you already wear.', 'Take care of last-minute details: sleep, hydration, hair.', 'Prepare a few inspiration images to guide the photographer.', 'On the day, let yourself be guided: a pose is built by two people.'],
    sections: [
      { h: 'Start by defining how your photos will be used', html: '<p>A portrait for a professional profile, for a couple, a family or for social media is not prepared in the same way. Before booking, answer one simple question: <strong>where will these photos be seen?</strong> Framing, outfit, mood and even location follow from it: a professional portrait calls for a plain backdrop and a composed expression, while a lifestyle session leaves more room for movement and setting.</p>' },
      { h: 'Choosing the location: outdoors or studio', html: '<p><strong>Outdoors</strong>, natural light gives lively images and a soft rendering, provided you pick the right time of day and accept a degree of unpredictability (weather, passers-by). <strong>In the studio</strong>, the light is fully controlled: a reassuring choice if you feel uneasy in public or want a neutral backdrop.</p><p>In our catalogue, the <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">individual photo session</a> takes place outdoors or in the studio (extra €80 for the studio on the Starter package). A mobile photographer can also travel to Béziers, Montpellier or Toulouse to find a suitable setting together.</p>' },
      { h: 'The outfit: comfort first', html: '<p>The best outfit is the one in which you feel like yourself. Favour clothes you have already worn, well ironed, in plain or low-contrast shades. Bring two or three options to vary the images. We cover the topic in detail in our article <a href="/conseils/que-porter-seance-photo/" data-nav="article:que-porter-seance-photo">What to wear for a photo session?</a>.</p>' },
      { h: 'Last-minute details', html: '<ul><li><strong>Sleep well</strong> the night before and drink water: a rested face shows.</li><li><strong>Avoid drastic changes</strong> (new haircut, new colour, unusual treatment) right before the session.</li><li><strong>Think about your hands</strong> and nails if they appear in the photos.</li><li><strong>Plan simple accessories</strong>: clean glasses, discreet jewellery, a watch.</li></ul>' },
      { h: 'Preparing inspiration', html: '<p>Gathering a few images you like (mood, colours, framing) helps you speak the same language. No need for a full file: three to five references are enough. Once your quote is confirmed, you can collect them in a <strong>personalised moodboard</strong> directly from your client area: art direction, mood, palette and inspiration (Pinterest, links).</p>' },
      { h: 'On the day: let yourself be guided', html: '<p>Arrive a few minutes early, without pressure. A good photographer guides you: where to put your hands, where to look, how to move. The Signature package includes posing guidance, and the Starter package a guided selection. Breathe, chat, laugh: the best images often come between two poses.</p><p>As for duration, allow about 1 hour for a Starter package, 2 hours for a Signature, a half-day for a Premium and a full day for the Editorial.</p>' },
      { h: 'After the session: selection and delivery', html: '<p>Your photos are sorted, carefully retouched, then delivered in high definition in a private gallery that you download from your client area. The delivery times shown on each package range from 5 to 10 working days, counted from the shoot date. You can then use the images commercially: usage rights are transferred to you with no time limit.</p>' },
      { h: 'Common mistakes to avoid', html: '<ul><li><strong>Choosing your outfit the night before</strong>, in a rush: try your options a few days earlier.</li><li><strong>Wearing uncomfortable clothes</strong>: discomfort shows on your face.</li><li><strong>Changing your appearance drastically</strong> just before the session.</li><li><strong>Keeping quiet about what you dislike</strong> (a profile, a smile): say so at the start, and the photographer will adapt the angles.</li><li><strong>Trying to pose all the time</strong>: alternate poses with moments of movement or conversation.</li></ul>' },
      { h: 'Professional or lifestyle portrait: what changes', html: '<p>The <strong>professional portrait</strong> serves an image of credibility: plain backdrop, outfit close to your profession, direct gaze, composed expression. The <strong>lifestyle portrait</strong> tells a personality: chosen location, movement, freer outfits, natural light. Many clients combine both in a single session, planning one outfit for each register.</p>' },
      { h: 'Which package to choose?', html: '<p>In our catalogue, four packages cover the usual needs: <strong>Starter</strong> (€290: 1-hour session, 8 retouched HD photos, guided selection), <strong>Signature</strong> (€490: 2 hours, 15 retouched HD photos, posing guidance), <strong>Premium</strong> (€790: half-day, up to 2 moods, 25 HD photos, 2 outfits) and <strong>Bunkaio editorial</strong> (€1,390: full day, 4 locations and 4 outfits, 30 HD photos, a short film). All include a private download gallery. Estimate your project in a few minutes with our <a href="/devis/" data-nav="quiz">online quote</a>.</p>' }
    ],
    faq: [
      { q: 'How many outfits should I bring?', a: 'Two or three are enough to vary the moods without losing time. Choose outfits that go well with the location and with each other.' },
      { q: 'I am not comfortable in front of the camera. Is that a problem?', a: 'No: it is the photographer’s job to put you at ease and guide your poses. Many people feel apprehensive about the session at first.' },
      { q: 'How long does a session last?', a: 'Depending on the package: 1 hour (Starter), 2 hours (Signature), a half-day (Premium) or a full day (Editorial).' }
    ]
  },
  'que-porter-seance-photo': {
    title: 'BUNKAIO ⊹ | What to wear for a photo session? Our advice',
    description: 'Colours, fabrics, cuts and accessories: the right outfits for a successful photo session, whether solo, as a couple or as a family.',
    h1: 'What to wear for a photo session?',
    excerpt: 'Colours, fabrics, patterns, accessories: our guidelines for choosing outfits that look like you and photograph well.',
    summary: ['Choose comfortable clothes in which you recognise yourself.', 'Favour plain or low-contrast shades, with no big logos.', 'As a couple or a family, coordinate colours without wearing the same thing.', 'Bring 2 or 3 outfits, ironed, with the right shoes.', 'Adapt your outfit to the use: professional, lifestyle, fashion.'],
    sections: [
      { h: 'The principle: an outfit that looks like you', html: '<p>A successful photo shows someone at ease. A brand-new outfit, one that is too tight or does not look like you shows immediately in the image. Choose clothes in which you move freely and whose cut you like.</p>' },
      { h: 'Colours', html: '<ul><li><strong>Plain or low-contrast shades</strong>: they keep attention on the face.</li><li><strong>Colours that flatter you</strong>: those you often get compliments on are good candidates.</li><li><strong>Watch the contrast with the setting</strong>: an outfit in the same shade as the background disappears, while a complementary colour stands out.</li></ul><p>For a couple or a family, start from a palette of two or three colours that harmonise (neutrals, earthy tones, pastels) rather than wearing the same outfit.</p>' },
      { h: 'Fabrics and patterns', html: '<p>Fluid or matte fabrics (cotton, linen, knitwear, fine wool) photograph well. Very shiny fabrics can create reflections, and very fine patterns (tight stripes, small checks) can cause distracting visual effects in the image. Big logos and written messages draw the eye away from the person.</p>' },
      { h: 'Accessories and details', html: '<ul><li>Keep jewellery and accessories <strong>discreet</strong> if you want the eye to stay on your face.</li><li><strong>Iron</strong> your clothes and check them in daylight (stains, loose threads, pilling).</li><li>Don’t forget the <strong>shoes</strong> and the belt: they appear as soon as the framing widens.</li><li>Plan <strong>suitable underwear</strong> for each outfit.</li></ul>' },
      { h: 'Adapting your outfit to how the photos will be used', html: '<p>For a professional portrait, favour an outfit close to the one you wear in your job, plain and well cut. For a lifestyle, couple or family session, look for naturalness: smart everyday outfits. For a fashion project, art direction comes first: see our article <a href="/conseils/preparer-shooting-mode-lookbook/" data-nav="article:preparer-shooting-mode-lookbook">Preparing a fashion shoot</a>.</p>' },
      { h: 'In summary', html: '<p>Bring two or three options and let the photographer help you choose on the spot according to the light and the setting. To learn everything about how the session unfolds, read our guide <a href="/conseils/preparer-seance-photo-portrait/" data-nav="article:preparer-seance-photo-portrait">Preparing your portrait photo session</a> or discover the <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">individual photo session</a>.</p>' },
      { h: 'What to wear depending on the type of session', html: '<p><strong>Professional portrait</strong>: a plain, well-cut outfit close to what you wear at work, in shades that flatter you. <strong>Lifestyle</strong>: smart everyday clothes, with one or two pieces that set you apart. <strong>Couple</strong>: two outfits that match through their palette without being identical. <strong>Family</strong>: a shared colour range (for example neutral tones with one accent colour) so that the group looks harmonious.</p>' },
      { h: 'What is better avoided', html: '<ul><li>Big printed <strong>logos and slogans</strong>.</li><li><strong>Very fine patterns</strong> (tight stripes, houndstooth) that can “vibrate” in the image.</li><li><strong>Brand-new clothes never worn</strong>: fold creases and discomfort.</li><li><strong>Outfits that are too tight</strong> or that crease easily.</li><li><strong>Colours identical to the setting</strong>, which blend you into the background.</li></ul>' },
      { h: 'The night-before checklist', html: '<ul><li>Outfits tried on, ironed and complete (top, bottom, shoes, accessories).</li><li>A spare option for each outfit.</li><li>Suitable underwear, with no visible marks.</li><li>Accessories and jewellery chosen and clean.</li><li>Your brief or inspiration images within reach.</li></ul>' }
    ],
    faq: [
      { q: 'Can I wear white or black?', a: 'Yes, as long as the outfit makes you feel comfortable. The photographer adjusts the exposure; what matters is checking the fabric and the cut. Just avoid very shiny outfits or very fine patterns.' },
      { q: 'Do I need to bring several outfits?', a: 'Two or three are enough: they let you vary the images without lengthening the session.' }
    ]
  },
  'preparer-shooting-photo-produit': {
    title: 'BUNKAIO ⊹ | Preparing a product photo shoot: checklist',
    description: 'Brief, product preparation, formats, mistakes to avoid: the checklist for a successful product photo shoot.',
    h1: 'Preparing a product photo shoot: brief, products and mistakes to avoid',
    excerpt: 'Packshots, styled shots, brief, product preparation: the steps for an efficient product photo shoot.',
    summary: ['Decide where your photos will be used: online shop, marketplace, social media, catalogue.', 'Tell packshots (neutral backdrop) and styled shots apart.', 'Prepare clean, complete products that are identical from one piece to the next.', 'Write a brief: product list, angles, backdrop, series consistency.', 'Check HD delivery and usage rights.'],
    sections: [
      { h: 'Packshot or styled shot?', html: '<p>The <strong>packshot</strong> shows the product alone, on a neutral backdrop and under controlled light: it is the reference format for an online shop or a marketplace. The <strong>styled shot</strong> shows the product being used, worn or installed in a setting: it tells a story and works well on social media or on a home page. Many brands combine both.</p>' },
      { h: 'Defining the use and the formats', html: '<p>List where the images will be published: product pages, banners, social media, brochures, adverts. Each medium has its own formats (square, vertical, panoramic). Say so before the shoot: it avoids cropping at the expense of the composition.</p>' },
      { h: 'Preparing the products', html: '<ul><li><strong>Cleanliness</strong>: dust them, remove fingerprints and unnecessary labels.</li><li><strong>Presentation</strong>: iron textiles, straighten shapes, check the fastenings.</li><li><strong>Completeness</strong>: packaging, accessories and leaflets to be photographed if needed.</li><li><strong>Consistency</strong>: favour items from the same batch to keep colours identical.</li><li><strong>Quantity</strong>: plan a spare item for fragile products.</li></ul>' },
      { h: 'Writing an effective brief', html: '<p>A good brief fits on one page: product list, desired angles for each (front, back, detail, scale), type of backdrop (white, coloured, textured), overall mood and visual references. You can also gather your inspiration in a <strong>moodboard</strong> from your client area once your quote is confirmed.</p>' },
      { h: 'Choosing the right package', html: '<p>Our <a href="/services/photo-produits-packshots/" data-nav="service:commercial">Commercial & products</a> catalogue starts at €390 with the Starter package (delivery in 3 working days) and goes up to the Editorial for more ambitious needs. The number of visuals, the options (Reels, styled shots) and the delivery times depend on the package: compare them before requesting your quote. To choose between a neutral backdrop and a styled setup, read <a href="/conseils/packshot-ou-mise-en-scene-photo-produit/" data-nav="article:packshot-ou-mise-en-scene-photo-produit">Packshot or styled product photo: which to choose?</a></p>' },
      { h: 'Delivery and usage rights', html: '<p>The images are retouched and delivered in high definition in a private gallery, and commercial usage rights are transferred to you with no time limit: you can use them on your website, your marketplaces and your adverts. Remember to ask which files and formats are supplied.</p>' },
      { h: 'Common mistakes in product photography', html: '<ul><li><strong>Dusty or marked products</strong>: every mark shows in high definition.</li><li><strong>Inconsistent series</strong>: different backdrops, angles or lighting from one photo to the next make a messy shop.</li><li><strong>Not prioritising</strong>: it is better to take care of your flagship products than to photograph everything at the same level.</li><li><strong>Neglecting details</strong>: textures, materials and finishes reassure the buyer.</li><li><strong>Forgetting formats</strong>: a square visual cannot always be cropped into a banner.</li></ul>' },
      { h: 'Marketplace, website or social media: adapting the visuals', html: '<p><strong>Marketplaces</strong> often impose rules (plain backdrop, proportions, resolution): check those of your platform before the shoot and put them in your brief. For an <strong>e-commerce website</strong>, think of a consistent series with several angles per product. For <strong>social media</strong>, add styled shots and vertical formats.</p>' },
      { h: 'The pre-shoot checklist', html: '<ul><li>Complete list of products, with references.</li><li>Clean products, ready to photograph, with spare items.</li><li>Brief: angles, backdrop, mood, formats and media.</li><li>Visual references or moodboard.</li><li>A contact who can be reached on the day of the shoot.</li></ul>' }
    ],
    faq: [
      { q: 'What is the difference between a packshot and a lifestyle photo?', a: 'A packshot shows the product alone on a neutral backdrop, while a lifestyle photo shows it in a context of use.' },
      { q: 'How many products can be photographed in one session?', a: 'It depends on the package you choose and on how complex the products are: state your list in the quote request.' }
    ]
  },
  'preparer-shooting-mode-lookbook': {
    title: 'BUNKAIO ⊹ | Preparing a fashion shoot: lookbook, e-commerce, portfolio',
    description: 'Lookbook, e-commerce, portfolio: how to prepare a fashion shoot (garments, casting, image rights, art direction).',
    h1: 'Preparing a fashion shoot: lookbook, e-commerce or portfolio',
    excerpt: 'Garments, casting, art direction, image rights: the checklist for preparing a fashion shoot calmly.',
    summary: ['Specify the type of shoot: lookbook, e-commerce, campaign or portfolio.', 'Prepare the garments (ironed, complete, right sizes) and the accessories.', 'Choose models, hair and make-up in line with the art direction.', 'Put the agreement on image rights and uses in writing.', 'Gather a moodboard: mood, colours, references.'],
    sections: [
      { h: 'What type of fashion shoot?', html: '<p>A <strong>lookbook</strong> presents a collection with a strong mood; an <strong>e-commerce</strong> shoot favours clear, consistent visuals that are quick to replicate; a <strong>campaign</strong> seeks brand image; a <strong>model portfolio</strong> shows the model’s versatility. Choosing the right format from the start avoids having to redo everything.</p>' },
      { h: 'Preparing garments and accessories', html: '<ul><li>Check that the outfits are <strong>complete</strong> (top, bottom, shoes, accessories).</li><li><strong>Iron or steam</strong> every piece, and plan what you need to adjust them on set (pins, adhesive tape).</li><li>Plan the <strong>right sizes</strong> for each model.</li><li>Gather the <strong>accessories</strong> (jewellery, bags, belts) that complete each look.</li></ul>' },
      { h: 'Casting, hair and make-up', html: '<p>The choice of model, hairstyle and make-up must serve your art direction: natural for e-commerce, more elaborate for a campaign. State these choices in your brief so that everyone works in the same direction.</p>' },
      { h: 'Image rights', html: '<p>Before the shoot, put in writing what has been agreed with the models: <strong>permitted uses</strong>, media, duration and territory, any fee. This protects the brand as well as the models. If in doubt, have your agreement reviewed by a legal professional.</p>' },
      { h: 'Building an art direction', html: '<p>Gather visual references: mood, colour palette, light, framing. Once your quote is confirmed, you can structure them in a <strong>moodboard</strong> from your client area, with the products or pieces to showcase, and exchange with the team through comments.</p>' },
      { h: 'Choosing the right package', html: '<p>Our <a href="/services/photographe-mode-mannequins/" data-nav="service:mode">Fashion, agencies & models</a> offer starts at €590 (Starter, delivery in 5 working days) and also includes a monthly subscription reserved for models. Compare the number of visuals, the outfits and the delivery times before requesting a quote. For raw photos intended for an agency, discover our <a href="/conseils/polas-mannequin-digitals-agence/" data-nav="article:polas-mannequin-digitals-agence">Polas and model digitals</a>.</p>' },
      { h: 'A typical shoot day', html: '<p>The day usually starts with <strong>set-up</strong> (lighting, set, rails), followed by a <strong>look test</strong> to validate the direction. Outfits are then shot in series, with regular <strong>breaks</strong> for the model and for hair or make-up changes. The day ends with details (accessories, close-ups) and packing up. Good preparation lets you do everything without rushing.</p>' },
      { h: 'Common mistakes', html: '<ul><li><strong>A brief that is too vague</strong>: without references, everyone imagines a different result.</li><li><strong>Garments not ironed or incomplete</strong>: shooting time is lost on preparation.</li><li><strong>Too many looks for the time available</strong>: fewer outfits, better photographed, is the better choice.</li><li><strong>A vague agreement on rights</strong>: specify uses and duration in writing.</li></ul>' },
      { h: 'Retouching and series consistency', html: '<p>Retouching must stay consistent from one visual to the next: same tones, same skin rendering, same proportions. State your expectations (natural, editorial, heavily smoothed or not) in the brief to avoid back-and-forth.</p>' }
    ],
    faq: [
      { q: 'Do I need to provide the models?', a: 'Specify it in your request: casting is part of the brief and can be organised with you depending on your project.' },
      { q: 'How can I get consistent visuals for an online shop?', a: 'Fix the backdrop, framing and lighting from the start, then keep them identical across the whole series.' }
    ]
  },
  'choisir-photographe-evenementiel': {
    title: 'BUNKAIO ⊹ | How to choose your event photographer',
    description: 'Criteria, questions to ask the provider and a preparation checklist to choose the right photo coverage for your event.',
    h1: 'How to choose your event photographer',
    excerpt: 'Selection criteria, questions to ask, how the day unfolds and a checklist: for event photo coverage with no unpleasant surprises.',
    summary: ['Define the key moments and the use of the photos (keepsakes, communication).', 'Compare portfolios on events similar to yours.', 'Check the quote: length, delivery times, usage rights, travel.', 'Provide a schedule and a list of people or moments not to be missed.', 'Warn guests and mention venue constraints (light, access).'],
    sections: [
      { h: 'Defining your needs', html: '<p>Start by clarifying the goal: <strong>keepsakes</strong> for guests, <strong>communication</strong> for a company, content for social media? Note the duration, the venue, the number of guests and the moments not to be missed (arrival, speeches, awards, cocktail, group portraits).</p>' },
      { h: 'Criteria for choosing', html: '<ul><li><strong>The portfolio</strong>: look for events close to yours (estate, company, reception).</li><li><strong>The style</strong>: discreet reportage, posed images, bright atmosphere or more contrasted.</li><li><strong>Discretion and responsiveness</strong>: a good event photographer fades into the background while capturing the moment.</li><li><strong>The contractual framework</strong>: length of coverage, delivery times, usage rights, travel costs.</li><li><strong>Quote transparency</strong>: what is included, what is optional.</li></ul>' },
      { h: 'Questions to ask before booking', html: '<ul><li>How long is the coverage included, and what happens if the event runs over?</li><li>How many retouched photos will be delivered, within what time, and in what form?</li><li>Are the usage rights (commercial use, duration) specified?</li><li>How are the photos shared (private gallery, download)?</li></ul>' },
      { h: 'Preparing the event', html: '<p>Give the photographer the <strong>schedule</strong> (times, places, highlights), the list of key people and a <strong>contact on site</strong>. If possible, arrange a venue visit to anticipate light, access and constraints. Let your guests know that a photographer is present.</p>' },
      { h: 'At BUNKAIO', html: '<p>Our <a href="/services/photographe-evenementiel/" data-nav="service:event">Events</a> service is aimed at estates, companies and receptions, with packages from €450 and retouched photos delivered in 3 to 10 working days depending on the package, in a private gallery. For a wedding, also discover <a href="/services/photobooth-ia-mariage-lumen/" data-nav="service:lumen">Lumen, our AI photobooth</a>.</p>' },
      { h: 'The ideal flow of a coverage', html: '<p>Before the event, the photographer arrives early to <strong>scout the venue</strong> and the light. During it, they follow the key moments of your programme (welcome, speeches, awards, cocktail) and plan time for <strong>group portraits</strong>. Afterwards, they sort and retouch the images before delivering them in an online gallery. The more precise your schedule, the more complete the coverage.</p>' },
      { h: 'Mistakes to avoid', html: '<ul><li><strong>Choosing on price alone</strong> without comparing what is included.</li><li><strong>Not providing the schedule</strong>: the photographer discovers the highlights at the last minute.</li><li><strong>Forgetting to name an on-site contact</strong> for access and the unexpected.</li><li><strong>Not planning group portraits</strong>: they need a dedicated moment.</li></ul>' },
      { h: 'Guests’ image rights', html: '<p>Let your guests know that a photographer is present. If the photos are used for your communication, make sure the people who can be recognised agree to this use, for example through a notice at the entrance or a written authorisation.</p>' }
    ],
    faq: [
      { q: 'How far in advance should I book?', a: 'As early as possible: slots are limited each month to guarantee the quality of every service.' },
      { q: 'Can the photos be used for my company’s communication?', a: 'Yes: commercial usage rights are transferred to you with no time limit.' }
    ]
  },
  'photobooth-mariage-bien-choisir': {
    title: 'BUNKAIO ⊹ | Wedding photobooth: how to choose the right one',
    description: 'Length, personalisation, prints, online gallery: the criteria and questions for choosing a wedding or event photobooth.',
    h1: 'Wedding photobooth: how to choose the right one',
    excerpt: 'Length of presence, branding, prints, online gallery: the points to check before booking a photobooth.',
    summary: ['Set the length of presence according to the flow of your evening.', 'Check the personalisation: backdrop, branding, palette.', 'Ask whether prints are limited or unlimited.', 'Make sure an online gallery is provided, and within what time.', 'Plan the location and the power supply with the venue.'],
    sections: [
      { h: 'What is a wedding photobooth for?', html: '<p>Beyond entertainment, a photobooth gives your guests an instant, personal keepsake, and the couple a collection of spontaneous images of the evening. Lumen, our AI photobooth, generates a unique keepsake in a few seconds, with the elegance expected at a high-end wedding.</p>' },
      { h: 'The criteria to compare', html: '<ul><li><strong>Length of presence</strong>: align it with the moments when your guests are available (cocktail, evening).</li><li><strong>Personalisation</strong>: backdrop, branding, colour palette in harmony with your decoration.</li><li><strong>Prints</strong>: limited or unlimited?</li><li><strong>The online gallery</strong>: are the photos delivered to you, and within what time?</li><li><strong>Installation</strong>: footprint, electricity, set-up and take-down time.</li></ul>' },
      { h: 'The Lumen packages', html: '<p>Lumen offers three packages: <strong>Essentials</strong> (€690: photobooth installed, up to 4 hours, unlimited prints, private gallery delivered within 7 days), <strong>Signature</strong> (€1,290: up to 6 hours, custom style with backdrop, branding and palette, unlimited prints, private gallery within 5 days) and <strong>Bespoke</strong> on quote. You will find the details on the <a href="/services/photobooth-ia-mariage-lumen/" data-nav="service:lumen">Lumen</a> page.</p>' },
      { h: 'Preparing the big day with your venue', html: '<ul><li>Ask the venue which location is possible and about access constraints.</li><li>Confirm that a power supply is nearby.</li><li>Tell the person coordinating the evening (wedding planner, caterer) the set-up time.</li><li>Inform your guests: an announcement or a small sign is enough to start the fun.</li></ul>' },
      { h: 'What if you also want a photographer?', html: '<p>A photobooth complements photo coverage; it does not replace it. To cover your event, read our guide <a href="/conseils/choisir-photographe-evenementiel/" data-nav="article:choisir-photographe-evenementiel">How to choose your event photographer</a>.</p>' },
      { h: 'How much time should you plan?', html: '<p>Work from your programme: a photobooth is mostly used during the cocktail and early in the evening, then more occasionally. The Lumen packages cover up to 4 hours (Essentials) or up to 6 hours (Signature): choose the duration that matches the time slots when your guests are really available.</p>' },
      { h: 'Mistakes to avoid', html: '<ul><li><strong>Booking without checking the personalisation</strong>: branding consistent with your decoration makes the difference.</li><li><strong>Forgetting the location</strong>: a corner that is too discreet or too noisy holds back use.</li><li><strong>Ignoring the power supply</strong> and access to the venue.</li><li><strong>Not telling the guests</strong>: an announcement kicks things off.</li></ul>' },
      { h: 'Questions to ask the provider', html: '<ul><li>How long is the presence and how long is the set-up?</li><li>What personalisation is possible (backdrop, branding, palette)?</li><li>Are prints unlimited?</li><li>Within what time is the online gallery delivered?</li><li>What happens if there is a technical problem during the evening?</li></ul>' }
    ],
    faq: [
      { q: 'Is Lumen only for weddings?', a: 'It is designed primarily for weddings, but it also suits private receptions, corporate events and evenings organised by event agencies.' },
      { q: 'Are prints limited?', a: 'On the Essentials and Signature packages, unlimited prints are included.' }
    ]
  },
  'polas-mannequin-digitals-agence': {
    title: 'BUNKAIO ⊹ | Polas and model digitals: what they are for',
    description: 'Polas (digitals): raw photos for modelling agencies. What they show, how to prepare and what the BUNKAIO package includes.',
    h1: 'Polas and model digitals: what are they for?',
    excerpt: 'Raw, unretouched photos made for agencies: what they show, how to prepare and what our Polas package includes.',
    summary: ['Polas (or digitals) are raw photos, with no retouching or styling, made for modelling agencies.', 'They are used to assess physique, posture and raw potential: face, profiles and full-length shots.', 'At BUNKAIO, the Polas package is shot in the studio on a white backdrop, with HD delivery within 24 hours.', 'For a polished portfolio or brand visuals, the Fashion packages apply.'],
    sections: [
      { h: 'What are polas (or digitals)?', html: '<p>Polas, also called digitals, are <strong>raw</strong> photos: no retouching, no styling, no effects. They are intended for <strong>modelling agencies</strong>, which look in them for a faithful image of the person as they are.</p>' },
      { h: 'What an agency looks for in them', html: '<p>Polas make it possible to assess a model’s <strong>physique</strong>, <strong>posture</strong> and <strong>raw potential</strong>. For this, the series generally includes the face, the profiles and full-length shots, on a neutral backdrop and under simple light.</p>' },
      { h: 'Preparing for a polas session', html: '<ul><li><strong>A simple, close-fitting outfit</strong> that shows the silhouette.</li><li><strong>Hair pulled back</strong> and a natural face, with little or no make-up.</li><li><strong>No accessories</strong> or conspicuous jewellery.</li><li><strong>Your agency’s instructions</strong>: they can vary from one agency to another, so ask for them before the session.</li></ul>' },
      { h: 'The Polas package at BUNKAIO', html: '<p>Our Polas package, offered within the <a href="/services/photographe-mode-mannequins/" data-nav="service:mode">Fashion, agencies & models</a> offer, is priced at <strong>€290</strong>, with the <strong>studio compulsory and included</strong> in the price. It includes:</p><ul><li>a studio session on a white backdrop, in neutral light;</li><li>raw photos, with no retouching or styling;</li><li>the face, the profiles and full-length shots;</li><li>HD files ready to send to your agency, delivered within 24 hours.</li></ul>' },
      { h: 'Polas or portfolio: what is the difference?', html: '<p>Polas are a presentation tool for agencies, not a communication visual. For a <strong>polished portfolio</strong>, a lookbook or brand visuals, the Fashion packages start at €590. Our guide <a href="/conseils/preparer-shooting-mode-lookbook/" data-nav="article:preparer-shooting-mode-lookbook">Preparing a fashion shoot</a> details the preparation.</p>' },
      { h: 'Getting a quote', html: '<p>The Polas package is selected in the <a href="/devis/" data-nav="quiz">online quote</a> for the Fashion category: estimate in 2 minutes, personalised reply within 48 hours, with no commitment.</p>' }
    ],
    faq: [
      { q: 'Are polas retouched?', a: 'No: they are raw photos, with no retouching or styling.' },
      { q: 'How soon are polas delivered?', a: 'The HD files are delivered within 24 hours.' },
      { q: 'Is the studio compulsory?', a: 'Yes: the Polas session takes place in the studio, on a white backdrop, and the studio is included in the price.' }
    ]
  },
  'packshot-ou-mise-en-scene-photo-produit': {
    title: 'BUNKAIO ⊹ | Packshot or styled photo: which to choose?',
    description: 'Neutral backdrop or styled product: which style for your product pages, website and social media? Selection criteria and BUNKAIO packages.',
    h1: 'Packshot or styled product photo: which to choose?',
    excerpt: 'Neutral backdrop for the product page, styled setup for social media: how to choose depending on the use, and which package to pick.',
    summary: ['The packshot isolates the product on a neutral backdrop: clear, faithful, ideal for product pages.', 'The styled shot places the product in a mood: it mainly serves social media and presentation pages.', 'Many shops need both: one packshot per product, plus a few mood images.', 'At BUNKAIO, the Starter package uses a neutral backdrop; styled shots are included from Signature.'],
    sections: [
      { h: 'The packshot: the product, nothing but the product', html: '<p>A packshot presents the product alone, on a <strong>neutral backdrop</strong>, with controlled light. It faithfully shows the shape, the material and the colours. It is the reference format for a product page: the visitor sees exactly what they are buying.</p>' },
      { h: 'The styled shot: the product in its universe', html: '<p>The styled photo places the product in a setting, with accessories, mood lighting and a visual point of view. It tells a use and a brand, and suits <strong>social media</strong>, the home page or communication materials.</p>' },
      { h: 'How to choose depending on the use', html: '<ul><li><strong>Product pages and catalogue</strong>: packshot on a neutral backdrop. Check the rules of your sales platform, as some impose a type of backdrop.</li><li><strong>Social media and communication</strong>: styled setup, to give your brand an identity.</li><li><strong>Launch or campaign</strong>: a mix of both, with a consistent series.</li></ul>' },
      { h: 'What our packages include', html: '<p>Our <a href="/services/photo-produits-packshots/" data-nav="service:commercial">Commercial & products</a> service covers both styles:</p><ul><li><strong>Starter, €390</strong>: up to 5 products, 10 retouched HD photos, neutral studio backdrop.</li><li><strong>Signature, €790</strong>: up to 12 products, 20 retouched HD photos, styled setup included.</li><li><strong>Premium, €1,390</strong>: up to 25 products, 35 retouched HD photos, styled setup included and 1 vertical product Reel.</li><li><strong>Bunkaio editorial, €2,390</strong>: full catalogue of 50 retouched HD photos, 1 brand film of 90 seconds and 2 vertical Reels.</li></ul>' },
      { h: 'Preparing well before choosing', html: '<p>List your products, the use of each image (product page, social media, advert) and the formats expected. Our checklist <a href="/conseils/preparer-shooting-photo-produit/" data-nav="article:preparer-shooting-photo-produit">Preparing a product photo shoot</a> guides you step by step. For an estimate, use the <a href="/devis/" data-nav="quiz">online quote</a>.</p>' }
    ],
    faq: [
      { q: 'Which package should I choose for product pages?', a: 'The Starter package offers photos on a neutral studio backdrop, suited to product pages: up to 5 products and 10 retouched HD photos.' },
      { q: 'Is the styled setup included?', a: 'Yes, from the Signature package.' },
      { q: 'Are usage rights included?', a: 'Yes: commercial usage rights are transferred to you with no time limit.' }
    ]
  },
  'lieux-seance-photo-montpellier-beziers-toulouse': {
    title: 'BUNKAIO ⊹ | Photo session locations in Montpellier, Béziers, Toulouse',
    description: 'Peyrou, Canal du Midi, Pont-Neuf, Plateau des Poètes: photogenic locations in Montpellier, Béziers and Toulouse, and how to choose yours.',
    h1: 'Where to hold a photo session in Montpellier, Béziers or Toulouse?',
    excerpt: 'Locations loved for their light and setting in the three cities where we work, and the criteria for choosing the right one.',
    summary: ['Montpellier, Béziers and Toulouse offer very different settings: stone and gardens, canal and cathedral, pink brick and riverbanks.', 'The best location depends on the mood you want, the season and the time of day: soft morning or late-afternoon light is the most flattering.', 'Some locations require permission depending on how the photos are used: we advise you when you request your quote.', 'BUNKAIO works in these three cities, with no fixed studio: the location is chosen with you.'],
    sections: [
      { h: 'How to choose the location of your session', html: '<ul><li><strong>The mood you want</strong>: classical architecture, nature, water, modern lines.</li><li><strong>The light</strong>: outdoors, early morning and late afternoon offer soft light.</li><li><strong>Crowds</strong>: a very touristy place is calmer early in the morning.</li><li><strong>Logistics</strong>: access, parking, walking between two settings if the package includes several locations.</li></ul>' },
      { h: 'In Montpellier', html: '<ul><li><strong>The Promenade du Peyrou</strong>: a vast esplanade with its triumphal arch, its equestrian statue of Louis XIV and its water tower, for elegant, highly architectural images.</li><li><strong>The Jardin des Plantes</strong>: the oldest botanical garden in France (1593), with shaded paths, greenhouses and fountains, for a natural, soothing look.</li><li><strong>The Écusson</strong>: lanes of the old town, mansions and stone façades, for an urban setting full of character.</li><li><strong>The Antigone district</strong>: Ricardo Bofill’s neoclassical architecture, its geometric lines and perspectives, for contemporary, stylised portraits.</li></ul>' },
      { h: 'In Béziers', html: '<ul><li><strong>The Canal du Midi and the nine Fonséranes locks</strong>: an emblematic site of the canal, for images where water and structures add depth.</li><li><strong>Saint-Nazaire Cathedral and the Pont Vieux</strong>: a view over the Orb valley, and a reflection of the cathedral in the water at dawn.</li><li><strong>The Plateau des Poètes</strong>: terraced gardens with a pond, a fountain, statues and varied vegetation.</li></ul>' },
      { h: 'In Toulouse', html: '<ul><li><strong>The Pont-Neuf and the Garonne riverbanks</strong>: pink-brick arches and warm light at the end of the day.</li><li><strong>The Quai de la Daurade</strong>: an urban setting on the banks of the Garonne, with a view of the Pont-Neuf.</li><li><strong>The Jardin des Plantes</strong>: a seven-hectare botanical garden near the Canal du Midi, combining greenery and Toulouse brick.</li><li><strong>The Canal du Midi</strong>: UNESCO-listed, with tree-lined banks, locks and bridges, particularly beautiful at dawn and dusk.</li></ul>' },
      { h: 'Permissions and uses', html: '<p>Personal sessions usually take place without difficulty in public places. For commercial use or a larger project, some municipalities or sites require permission: state the intended use in your request and we will advise you on the most suitable location.</p>' },
      { h: 'Choosing your package', html: '<p>An outdoor session can take place in one or several locations depending on the package: the Bunkaio editorial package, for example, includes a full day across 4 different locations. Discover our <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">individual photo session</a>, or read <a href="/conseils/preparer-seance-photo-portrait/" data-nav="article:preparer-seance-photo-portrait">how to prepare your portrait session</a>. For an estimate, use the <a href="/devis/" data-nav="quiz">online quote</a>.</p>' }
    ],
    faq: [
      { q: 'In which cities do you work?', a: 'In Béziers, Montpellier and Toulouse. Travel is free in Montpellier and Béziers; it is charged in Toulouse and in any other city in France.' },
      { q: 'Can I choose several locations during the session?', a: 'Yes, depending on the package: the Bunkaio editorial package includes a full day across 4 different locations.' },
      { q: 'Do I need permission to take photos in a public place?', a: 'For a personal session, generally not; for commercial use, some places require it. State the use in your request.' }
    ]
  },
  'portrait-professionnel-photo-profil-linkedin': {
    title: 'BUNKAIO ⊹ | Professional portrait: profile photo, website, team',
    description: 'LinkedIn profile photo, website, team: how to get a successful professional portrait, what to wear and which package to choose.',
    h1: 'Professional portrait: getting a great profile and presentation photo',
    excerpt: 'For LinkedIn, your website or your team: the keys to a natural professional portrait, and the right package.',
    summary: ['A professional portrait is meant to inspire trust: natural, sharp, consistent with your profession.', 'Plan the uses (profile, website, press, team) before the session: they determine the framing and the formats.', 'A simple, comfortable, plain outfit works better than one bought for the occasion.', 'At BUNKAIO, portrait sessions start at €390, with commercial usage rights transferred with no time limit.'],
    sections: [
      { h: 'What is a professional portrait for?', html: '<p>Your portrait is often the first contact with your clients or recruiters: LinkedIn profile, website, team presentation, press article, email signature. It must reflect your profession while remaining natural.</p>' },
      { h: 'Defining the uses before the session', html: '<ul><li><strong>Online profile</strong>: tight framing on the face and shoulders.</li><li><strong>Website</strong>: wider framing, possibly with a setting related to your activity.</li><li><strong>Team</strong>: a consistent style for everyone, in individual sessions or as a <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">group</a>.</li><li><strong>Press and communication</strong>: horizontal and vertical formats.</li></ul>' },
      { h: 'What to wear?', html: '<p>Choose a plain, comfortable outfit close to what you wear at work. Solid colours work well; avoid overly contrasted patterns. Our guide <a href="/conseils/que-porter-seance-photo/" data-nav="article:que-porter-seance-photo">What to wear for a photo session?</a> covers colours and fabrics in detail.</p>' },
      { h: 'Outdoors or studio?', html: '<p>Outdoors gives a lively, bright look; the studio offers a controlled, uniform backdrop, useful for a team. On the Starter package, the studio is available with an extra €80. To choose a location, see <a href="/conseils/lieux-seance-photo-montpellier-beziers-toulouse/" data-nav="article:lieux-seance-photo-montpellier-beziers-toulouse">our location ideas in Montpellier, Béziers and Toulouse</a>.</p>' },
      { h: 'Which package to choose?', html: '<p>For a professional portrait, two packages are often enough: <strong>Starter, €390</strong> (1-hour session, 8 retouched HD photos, guided selection, delivery in 5 working days) or <strong>Signature, €690</strong> (2-hour session, 15 retouched HD photos, posing guidance, delivery in 7 working days). Commercial usage rights are transferred to you with no time limit. Find all the packages on the <a href="/services/portrait-professionnel-corporate/" data-nav="service:corporate">Corporate — professional portraits</a> page.</p>' },
      { h: 'Getting an estimate', html: '<p>The <a href="/devis/" data-nav="quiz">online quote</a> takes 2 minutes: you receive a personalised reply within 48 hours, with no commitment. Mention that the portrait is intended for professional use.</p>' }
    ],
    faq: [
      { q: 'Can the photos be used on LinkedIn and on my website?', a: 'Yes: commercial usage rights are transferred to you with no time limit.' },
      { q: 'Can a whole team be photographed?', a: 'Yes: sessions are possible solo, as a couple or as a group, outdoors or in the studio.' },
      { q: 'How soon are the photos delivered?', a: 'Between 5 and 10 working days depending on the package chosen.' }
    ]
  }
};
