/* ═══════════════════════════════════════════════════════════
   ARTICLES DE CONSEILS — config/articles.js
   Source unique des pages /conseils/ et /conseils/<article>/.
   Pour ajouter un article : copier un bloc, changer le slug, puis relancer
   `node tools/build-routes.cjs`. Les liens internes utilisent data-nav
   ("service:<catégorie>", "article:<slug>", "quiz", "faq", "contact"…).
   Les faits cités (prix, durées, délais, contenu des formules) viennent du
   catalogue du site — à tenir à jour si le catalogue change.
   ═══════════════════════════════════════════════════════════ */
const ARTICLES = [
  {
    slug: 'combien-coute-une-seance-photo',
    cat: 'photo-part',
    title: 'Combien coûte une séance photo ? Tarifs et facteurs | BUNKAIO',
    description: 'Durée, lieu, nombre de photos retouchées, droits : ce qui fait varier le prix d\'une séance photo, avec nos tarifs réels.',
    h1: 'Combien coûte une séance photo ?',
    excerpt: 'Ce qui fait varier le prix d\'une séance photo portrait, nos tarifs réels et les questions à poser pour comparer deux devis.',
    date: '2026-10-02', minutes: 5,
    summary: ['Le prix dépend surtout de la durée, du lieu, du nombre de photos retouchées et des droits d\'utilisation.', 'Chez BUNKAIO, une séance portrait commence à 230 € HT et va jusqu\'à 990 € HT.', 'Comparez deux devis sur les mêmes critères : durée, photos retouchées, délais, droits, déplacement.', 'Le devis en ligne donne une estimation en 2 minutes, avec une réponse personnalisée sous 48 h.'],
    related: ['preparer-seance-photo-portrait', 'que-porter-seance-photo'],
    sections: [
      { h: 'Ce qui fait varier le prix d\'une séance photo', html: '<ul><li><strong>La durée</strong> : une heure de séance ne coûte pas autant qu\'une demi-journée ou une journée complète.</li><li><strong>Le lieu</strong> : extérieur ou studio, nombre de lieux différents, frais de déplacement.</li><li><strong>Le nombre de photos retouchées</strong> livrées : la retouche représente un temps de travail important après la séance.</li><li><strong>Le nombre de tenues ou d\'ambiances</strong> prévues.</li><li><strong>La direction artistique</strong> : accompagnement sur les poses, le style, la préparation.</li><li><strong>Les droits d\'utilisation</strong> : usage personnel ou commercial, durée.</li><li><strong>Les délais</strong> de livraison.</li></ul>' },
      { h: 'Les tarifs d\'une séance portrait chez BUNKAIO', html: '<p>Notre catalogue <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">Séance photo particuliers</a> compte quatre formules, tarifs hors taxes :</p><ul><li><strong>Découverte, 230 € HT</strong> : 1 h de séance, 8 photos HD retouchées, sélection guidée, livraison en 5 jours ouvrés.</li><li><strong>Signature, 390 € HT</strong> : 2 h de séance, 15 photos HD retouchées, direction de pose, livraison en 7 jours ouvrés.</li><li><strong>Premium, 590 € HT</strong> : demi-journée, jusqu\'à 2 ambiances, 25 photos HD retouchées, 2 tenues, livraison en 7 jours ouvrés.</li><li><strong>Éditorial Bunkaio, 990 € HT</strong> : journée complète, 4 lieux et 4 tenues différentes, 30 photos HD retouchées, un film court, livraison en 10 jours ouvrés.</li></ul><p>Toutes comprennent une galerie privée de téléchargement. Le studio en supplément de l\'extérieur est de 60 € sur la formule Découverte.</p>' },
      { h: 'Séance de particuliers ou séance professionnelle : ce qui change', html: '<p>Une séance pour vous, votre couple ou votre famille se concentre sur la relation et le naturel. Un projet professionnel (marque, entreprise, produits) demande en plus un brief, des formats précis et des droits d\'usage commerciaux. Nos formules <a href="/services/photo-produits-packshots/" data-nav="service:commercial">Commercial & produits</a> et <a href="/services/photographe-mode-mannequins/" data-nav="service:mode">Mode</a> répondent à ces besoins avec leurs propres tarifs.</p>' },
      { h: 'Les questions à poser pour comparer deux devis', html: '<ul><li>Quelle est la <strong>durée</strong> de la séance ?</li><li>Combien de photos <strong>retouchées</strong> sont livrées, et en quelle résolution ?</li><li>Quel est le <strong>délai de livraison</strong> ?</li><li>Quels <strong>droits d\'utilisation</strong> sont cédés (usage commercial, durée) ?</li><li>Y a-t-il des <strong>frais de déplacement</strong> ?</li><li>Quelles sont les <strong>modalités de paiement</strong> et d\'annulation ?</li></ul>' },
      { h: 'Paiement et annulation chez BUNKAIO', html: '<p>Un acompte de 30 % est versé à la commande (signature du devis) et le solde à la livraison. Le paiement peut se faire par carte bancaire, prélèvement automatique ou en 3 fois sans frais avec Klarna. Après la validation du devis, l\'acompte reste acquis à BUNKAIO en cas d\'annulation de votre part. Plus de détails dans la <a href="/faq/" data-nav="faq">FAQ</a>.</p>' },
      { h: 'Obtenir une estimation précise', html: '<p>Le plus simple est de passer par notre <a href="/devis/" data-nav="quiz">devis en ligne</a> : en 2 minutes, vous choisissez votre univers, votre formule et vos options, et vous recevez une réponse personnalisée sous 48 h, sans engagement.</p>' },
    ],
    faq: [
      { q: 'Le studio est-il en supplément ?', a: 'Sur la formule Découverte, la séance se fait en extérieur ou en studio, avec un supplément de 60 € pour le studio.' },
      { q: 'Peut-on payer en plusieurs fois ?', a: 'Oui : carte bancaire, prélèvement automatique ou 3 fois sans frais avec Klarna.' },
      { q: 'Les photos sont-elles utilisables à titre commercial ?', a: 'Oui : les droits d\'utilisation commerciale vous sont cédés sans limite de durée.' },
    ],
  },
  {
    slug: 'preparer-seance-photo-portrait',
    cat: 'photo-part',
    title: 'Préparer sa séance photo portrait : guide complet | BUNKAIO',
    description: 'Choisir le lieu, la tenue, la lumière et se préparer : conseils concrets pour réussir une séance photo portrait naturelle et sans stress.',
    h1: 'Préparer sa séance photo portrait : le guide complet',
    excerpt: 'Lieu, tenue, préparation, jour J : tout ce qu\'il faut savoir pour une séance photo portrait naturelle et réussie.',
    date: '2026-10-02', minutes: 5,
    summary: ['Définissez l\'usage de vos photos avant de choisir le style et le lieu.', 'Optez pour des tenues confortables que vous portez déjà.', 'Soignez les détails de dernière minute : sommeil, hydratation, coiffure.', 'Préparez quelques inspirations pour guider le photographe.', 'Le jour J, laissez-vous guider : la pose se construit à deux.'],
    related: ['que-porter-seance-photo', 'preparer-shooting-photo-produit'],
    sections: [
      { h: 'Commencez par définir l\'usage de vos photos', html: '<p>Un portrait pour un profil professionnel, pour un couple, une famille ou pour vos réseaux sociaux ne se prépare pas de la même façon. Avant de réserver, répondez à une question simple : <strong>où ces photos seront-elles vues ?</strong> Le cadrage, la tenue, l\'ambiance et même le lieu en découlent : un portrait professionnel demande un fond sobre et une expression posée, alors qu\'une séance lifestyle laisse plus de place au mouvement et au décor.</p>' },
      { h: 'Choisir le lieu : extérieur ou studio', html: '<p><strong>En extérieur</strong>, la lumière naturelle donne des images vivantes et un rendu souple, à condition de choisir le bon moment de la journée et d\'accepter une part d\'imprévu (météo, passage). <strong>En studio</strong>, la lumière est entièrement maîtrisée : c\'est un choix rassurant si vous êtes mal à l\'aise en public ou si vous voulez un fond neutre.</p><p>Dans notre catalogue, la séance <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">photo particuliers</a> se déroule en extérieur ou en studio (supplément de 60 € pour le studio sur la formule Découverte). Un photographe mobile peut aussi se déplacer à Béziers, Montpellier ou Toulouse pour trouver ensemble un décor adapté.</p>' },
      { h: 'La tenue : confort avant tout', html: '<p>La meilleure tenue est celle dans laquelle vous vous sentez vous-même. Privilégiez des vêtements que vous avez déjà portés, bien repassés, dans des teintes unies ou peu contrastées. Apportez deux ou trois options pour varier les images. Nous avons détaillé le sujet dans notre article <a href="/conseils/que-porter-seance-photo/" data-nav="article:que-porter-seance-photo">Que porter pour une séance photo ?</a>.</p>' },
      { h: 'Les détails de dernière minute', html: '<ul><li><strong>Dormez bien</strong> la veille et buvez de l\'eau : le visage reposé se voit.</li><li><strong>Évitez les changements radicaux</strong> (nouvelle coupe, nouvelle couleur, soin inhabituel) juste avant la séance.</li><li><strong>Pensez aux mains</strong> et aux ongles si elles apparaissent sur les photos.</li><li><strong>Prévoyez des accessoires simples</strong> : lunettes propres, bijoux discrets, une montre.</li></ul>' },
      { h: 'Préparer des inspirations', html: '<p>Rassembler quelques images qui vous plaisent (ambiance, couleurs, cadrages) aide à parler le même langage. Pas besoin d\'un dossier complet : trois à cinq références suffisent. Une fois votre devis confirmé, vous pouvez les rassembler dans un <strong>moodboard personnalisé</strong> directement depuis votre espace client : direction artistique, ambiance, palette et inspirations (Pinterest, liens).</p>' },
      { h: 'Le jour J : se laisser guider', html: '<p>Arrivez quelques minutes en avance, sans pression. Un bon photographe vous guide : où poser les mains, où regarder, comment bouger. La formule Signature inclut d\'ailleurs la direction de pose, et la Découverte une sélection guidée. Respirez, discutez, riez : les meilleures images arrivent souvent entre deux poses.</p><p>Côté durée, comptez environ 1 h pour une formule Découverte, 2 h pour une Signature, une demi-journée pour une Premium et une journée complète pour l\'Éditorial.</p>' },
      { h: 'Après la séance : sélection et livraison', html: '<p>Vos photos sont triées, retouchées avec soin, puis livrées en haute définition dans une galerie privée à télécharger depuis votre espace client. Les délais indiqués sur chaque formule vont de 5 à 10 jours ouvrés, à partir de la date du shooting. Vous pouvez ensuite utiliser les images à titre commercial : les droits d\'utilisation vous sont cédés sans limite de durée.</p>' },
      { h: 'Les erreurs fréquentes à éviter', html: '<ul><li><strong>Choisir sa tenue la veille</strong>, dans l\'urgence : essayez vos options quelques jours avant.</li><li><strong>Porter un vêtement inconfortable</strong> : la gêne se lit sur le visage.</li><li><strong>Changer radicalement d\'apparence</strong> juste avant la séance.</li><li><strong>Garder pour soi ce qu\'on n\'aime pas</strong> (un profil, un sourire) : dites-le dès le début, le photographe adaptera les angles.</li><li><strong>Vouloir poser en permanence</strong> : alternez poses et moments de mouvement ou de conversation.</li></ul>' },
      { h: 'Portrait professionnel ou lifestyle : ce qui change', html: '<p>Le <strong>portrait professionnel</strong> sert une image de crédibilité : fond sobre, tenue proche de votre métier, regard direct, expression posée. Le <strong>portrait lifestyle</strong> raconte une personnalité : lieu choisi, mouvement, tenues plus libres, lumière naturelle. Beaucoup de clients combinent les deux dans une même séance, en prévoyant une tenue par registre.</p>' },
      { h: 'Quelle formule choisir ?', html: '<p>Dans notre catalogue, quatre formules couvrent les besoins courants : <strong>Découverte</strong> (230 € HT : 1 h de séance, 8 photos HD retouchées, sélection guidée), <strong>Signature</strong> (390 € HT : 2 h, 15 photos HD retouchées, direction de pose), <strong>Premium</strong> (590 € HT : demi-journée, jusqu\'à 2 ambiances, 25 photos HD, 2 tenues) et <strong>Éditorial Bunkaio</strong> (990 € HT : journée complète, 4 lieux et 4 tenues, 30 photos HD, un film court). Toutes comprennent une galerie privée de téléchargement. Estimez votre projet en quelques minutes avec notre <a href="/devis/" data-nav="quiz">devis en ligne</a>.</p>' },
    ],
    faq: [
      { q: 'Combien de tenues faut-il apporter ?', a: 'Deux ou trois suffisent pour varier les ambiances sans perdre de temps. Choisissez des tenues qui se coordonnent avec le lieu et entre elles.' },
      { q: 'Je ne suis pas à l\'aise devant l\'objectif, est-ce un problème ?', a: 'Non : c\'est le rôle du photographe de vous mettre en confiance et de vous guider sur les poses. Beaucoup de personnes appréhendent la séance au départ.' },
      { q: 'Combien de temps dure une séance ?', a: 'Selon la formule : 1 h (Découverte), 2 h (Signature), une demi-journée (Premium) ou une journée complète (Éditorial).' },
    ],
  },
  {
    slug: 'que-porter-seance-photo',
    cat: 'photo-part',
    title: 'Que porter pour une séance photo ? Nos conseils | BUNKAIO',
    description: 'Couleurs, matières, coupes et accessoires : les bonnes tenues pour une séance photo réussie, en portrait, en couple ou en famille.',
    h1: 'Que porter pour une séance photo ?',
    excerpt: 'Couleurs, matières, motifs, accessoires : nos repères pour choisir des tenues qui vous ressemblent et se photographient bien.',
    date: '2026-10-02', minutes: 4,
    summary: ['Choisissez des vêtements confortables dans lesquels vous vous reconnaissez.', 'Privilégiez les teintes unies ou peu contrastées, sans gros logos.', 'En couple ou en famille, coordonnez les couleurs sans porter la même chose.', 'Apportez 2 ou 3 tenues, repassées, avec les bonnes chaussures.', 'Adaptez la tenue à l\'usage : professionnel, lifestyle, mode.'],
    related: ['preparer-seance-photo-portrait', 'preparer-shooting-mode-lookbook'],
    sections: [
      { h: 'Le principe : une tenue qui vous ressemble', html: '<p>Une photo réussie montre une personne à l\'aise. Une tenue neuve, trop serrée ou qui ne vous ressemble pas se voit immédiatement sur l\'image. Choisissez des vêtements dans lesquels vous bougez librement, et dont vous aimez la coupe.</p>' },
      { h: 'Les couleurs', html: '<ul><li><strong>Teintes unies ou peu contrastées</strong> : elles gardent l\'attention sur le visage.</li><li><strong>Couleurs qui vous flattent</strong> : celles que l\'on vous complimente souvent sont de bons candidats.</li><li><strong>Attention au contraste avec le décor</strong> : une tenue de la même teinte que le fond disparaît, une couleur complémentaire ressort.</li></ul><p>Pour un couple ou une famille, partez d\'une palette de deux ou trois couleurs qui s\'harmonisent (neutres, tons terreux, pastels) plutôt que de porter la même tenue.</p>' },
      { h: 'Les matières et les motifs', html: '<p>Les matières fluides ou mates (coton, lin, maille, laine fine) se photographient bien. Les tissus très brillants peuvent créer des reflets, et les motifs très fins (rayures serrées, petits carreaux) peuvent provoquer des effets visuels gênants à l\'image. Les gros logos et les messages écrits attirent le regard au détriment de la personne.</p>' },
      { h: 'Les accessoires et les détails', html: '<ul><li>Gardez des bijoux et accessoires <strong>discrets</strong> si vous voulez que le regard reste sur votre visage.</li><li><strong>Repassez</strong> vos vêtements et vérifiez-les à la lumière du jour (taches, fils, boulochage).</li><li>N\'oubliez pas les <strong>chaussures</strong> et la ceinture : elles apparaissent dès que le cadrage s\'élargit.</li><li>Prévoyez des <strong>sous-vêtements adaptés</strong> à chaque tenue.</li></ul>' },
      { h: 'Adapter la tenue à l\'usage de vos photos', html: '<p>Pour un portrait professionnel, privilégiez une tenue proche de celle que vous portez dans votre métier, sobre et bien coupée. Pour une séance lifestyle, couple ou famille, cherchez le naturel : tenues du quotidien soignées. Pour un projet mode, la direction artistique prime : voir notre article <a href="/conseils/preparer-shooting-mode-lookbook/" data-nav="article:preparer-shooting-mode-lookbook">Préparer un shooting mode</a>.</p>' },
      { h: 'En résumé', html: '<p>Apportez deux ou trois options et laissez le photographe vous aider à choisir sur place en fonction de la lumière et du décor. Pour tout savoir sur le déroulé, consultez notre guide <a href="/conseils/preparer-seance-photo-portrait/" data-nav="article:preparer-seance-photo-portrait">Préparer sa séance photo portrait</a> ou découvrez la <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">séance photo particuliers</a>.</p>' },
      { h: 'Que porter selon le type de séance ?', html: '<p><strong>Portrait professionnel</strong> : une tenue sobre et bien coupée, proche de celle que vous portez au travail, dans des teintes qui vous flattent. <strong>Lifestyle</strong> : des vêtements du quotidien soignés, avec une ou deux pièces qui vous distinguent. <strong>Couple</strong> : deux tenues qui s\'accordent par leur palette sans être identiques. <strong>Famille</strong> : une gamme de couleurs commune (par exemple des tons neutres avec une couleur d\'accent) pour que le groupe paraisse harmonieux.</p>' },
      { h: 'Ce qu\'il vaut mieux éviter', html: '<ul><li>Les <strong>gros logos et slogans</strong> imprimés.</li><li>Les <strong>motifs très fins</strong> (rayures serrées, pied-de-poule) qui peuvent « vibrer » à l\'image.</li><li>Les <strong>vêtements neufs jamais portés</strong> : plis de pliage et inconfort.</li><li>Les <strong>tenues trop serrées</strong> ou qui se froissent facilement.</li><li>Les <strong>couleurs identiques au décor</strong>, qui vous fondent dans le fond.</li></ul>' },
      { h: 'La check-list de la veille', html: '<ul><li>Tenues essayées, repassées, complètes (haut, bas, chaussures, accessoires).</li><li>Une option de rechange pour chaque tenue.</li><li>Sous-vêtements adaptés, sans marques visibles.</li><li>Accessoires et bijoux choisis, propres.</li><li>Votre brief ou vos inspirations à portée de main.</li></ul>' },
    ],
    faq: [
      { q: 'Peut-on porter du blanc ou du noir ?', a: 'Oui, tant que la tenue vous met à l\'aise. Le photographe ajuste l\'exposition ; l\'essentiel est de vérifier la matière et la coupe. Évitez simplement les tenues très brillantes ou les motifs très fins.' },
      { q: 'Faut-il apporter plusieurs tenues ?', a: 'Deux ou trois suffisent : cela permet de varier les images sans allonger la séance.' },
    ],
  },
  {
    slug: 'preparer-shooting-photo-produit',
    cat: 'commercial',
    title: 'Préparer un shooting photo produit : check-list | BUNKAIO',
    description: 'Brief, préparation des produits, formats, erreurs à éviter : la check-list pour réussir votre prochain shooting photo produit.',
    h1: 'Préparer un shooting photo produit : brief, produits et erreurs à éviter',
    excerpt: 'Packshot, mise en situation, brief, préparation des produits : les étapes pour un shooting photo produit efficace.',
    date: '2026-10-02', minutes: 5,
    summary: ['Décidez où vos photos seront utilisées : boutique, marketplace, réseaux, catalogue.', 'Distinguez packshot (fond neutre) et mise en situation.', 'Préparez des produits propres, complets et identiques d\'une pièce à l\'autre.', 'Rédigez un brief : liste des produits, angles, fond, cohérence de série.', 'Vérifiez la livraison en haute définition et les droits d\'utilisation.'],
    related: ['preparer-shooting-mode-lookbook', 'preparer-seance-photo-portrait'],
    sections: [
      { h: 'Packshot ou mise en situation ?', html: '<p>Le <strong>packshot</strong> présente le produit seul, sur fond neutre et en lumière maîtrisée : c\'est le format de référence pour une boutique en ligne ou une marketplace. La <strong>mise en situation</strong> montre le produit utilisé, porté ou installé dans un décor : elle raconte une histoire et fonctionne bien sur les réseaux sociaux ou en page d\'accueil. Beaucoup de marques combinent les deux.</p>' },
      { h: 'Définir l\'usage et les formats', html: '<p>Listez où les images seront publiées : fiches produit, bannières, réseaux sociaux, brochures, publicités. Chaque support a ses formats (carré, vertical, panoramique). Dites-le avant le shooting : cela évite de recadrer au détriment de la composition.</p>' },
      { h: 'Préparer les produits', html: '<ul><li><strong>Propreté</strong> : dépoussiérez, enlevez traces de doigts et étiquettes inutiles.</li><li><strong>Tenue</strong> : repassez textiles, redressez les formes, vérifiez les fermetures.</li><li><strong>Complétude</strong> : packaging, accessoires, notices à photographier si nécessaire.</li><li><strong>Cohérence</strong> : privilégiez des exemplaires du même lot pour garder des couleurs identiques.</li><li><strong>Quantité</strong> : prévoyez un exemplaire de rechange pour les produits fragiles.</li></ul>' },
      { h: 'Rédiger un brief efficace', html: '<p>Un bon brief tient sur une page : liste des produits, angles souhaités pour chacun (face, dos, détail, échelle), type de fond (blanc, coloré, texturé), ambiance générale et références visuelles. Vous pouvez aussi rassembler vos inspirations dans un <strong>moodboard</strong> depuis votre espace client une fois votre devis confirmé.</p>' },
      { h: 'Choisir la bonne formule', html: '<p>Notre catalogue <a href="/services/photo-produits-packshots/" data-nav="service:commercial">Commercial & produits</a> démarre à 350 € HT avec la formule Découverte (livraison en 3 jours ouvrés) et monte jusqu\'à l\'Éditorial pour les besoins plus ambitieux. Le nombre de visuels, les options (Reels, mises en situation) et les délais dépendent de la formule : comparez-les avant de demander votre devis. Pour choisir entre fond neutre et mise en scène, lisez <a href="/conseils/packshot-ou-mise-en-scene-photo-produit/" data-nav="article:packshot-ou-mise-en-scene-photo-produit">Packshot ou photo mise en scène : que choisir ?</a></p>' },
      { h: 'Livraison et droits d\'utilisation', html: '<p>Les images sont retouchées, livrées en haute définition dans une galerie privée, et les droits d\'utilisation commerciale vous sont cédés sans limite de durée : vous pouvez les utiliser sur votre site, vos marketplaces et vos publicités. Pensez à demander quels fichiers et quels formats sont fournis.</p>' },
      { h: 'Les erreurs fréquentes en photo produit', html: '<ul><li><strong>Produits poussiéreux ou marqués</strong> : chaque trace se voit en haute définition.</li><li><strong>Séries incohérentes</strong> : des fonds, angles ou lumières différents d\'une photo à l\'autre donnent une boutique brouillonne.</li><li><strong>Ne pas hiérarchiser</strong> : mieux vaut soigner vos produits phares que tout photographier au même niveau.</li><li><strong>Négliger les détails</strong> : textures, matières et finitions rassurent l\'acheteur.</li><li><strong>Oublier les formats</strong> : un visuel carré ne se recadre pas toujours en bannière.</li></ul>' },
      { h: 'Marketplace, site ou réseaux : adapter les visuels', html: '<p>Les <strong>marketplaces</strong> imposent souvent des règles (fond uni, proportions, résolution) : vérifiez celles de votre plateforme avant le shooting et indiquez-les dans votre brief. Pour un <strong>site e-commerce</strong>, pensez à une série homogène avec plusieurs angles par produit. Pour les <strong>réseaux sociaux</strong>, ajoutez des mises en situation et des formats verticaux.</p>' },
      { h: 'La check-list avant le shooting', html: '<ul><li>Liste complète des produits, avec références.</li><li>Produits propres, prêts à photographier, exemplaires de rechange.</li><li>Brief : angles, fond, ambiance, formats et supports.</li><li>Références visuelles ou moodboard.</li><li>Contact joignable le jour du shooting.</li></ul>' },
    ],
    faq: [
      { q: 'Quelle différence entre packshot et photo lifestyle ?', a: 'Le packshot montre le produit seul sur fond neutre, la photo lifestyle le met en scène dans un contexte d\'usage.' },
      { q: 'Combien de produits peut-on photographier en une séance ?', a: 'Cela dépend de la formule choisie et de la complexité des produits : précisez votre liste dans la demande de devis.' },
    ],
  },
  {
    slug: 'preparer-shooting-mode-lookbook',
    cat: 'mode',
    title: 'Préparer un shooting mode : lookbook, e-commerce, book | BUNKAIO',
    description: 'Lookbook, e-commerce, book : comment préparer un shooting mode (pièces, casting, droit à l\'image, direction artistique).',
    h1: 'Préparer un shooting mode : lookbook, e-commerce ou book',
    excerpt: 'Pièces, casting, direction artistique, droit à l\'image : la check-list pour préparer un shooting mode sereinement.',
    date: '2026-10-02', minutes: 5,
    summary: ['Précisez le type de shooting : lookbook, e-commerce, campagne ou book.', 'Préparez les pièces (repassées, complètes, bonnes tailles) et les accessoires.', 'Choisissez modèles, coiffure et maquillage en accord avec la direction artistique.', 'Formalisez par écrit l\'accord sur le droit à l\'image et les usages.', 'Rassemblez un moodboard : ambiance, couleurs, références.'],
    related: ['que-porter-seance-photo', 'preparer-shooting-photo-produit'],
    sections: [
      { h: 'Quel type de shooting mode ?', html: '<p>Un <strong>lookbook</strong> présente une collection avec une ambiance forte ; un shooting <strong>e-commerce</strong> privilégie des visuels clairs, homogènes et rapides à décliner ; une <strong>campagne</strong> cherche l\'image de marque ; un <strong>book de mannequin</strong> montre la polyvalence du modèle. Choisir le bon format au départ évite d\'avoir à tout refaire.</p>' },
      { h: 'Préparer les pièces et les accessoires', html: '<ul><li>Vérifiez la <strong>complétude</strong> des tenues (haut, bas, chaussures, accessoires).</li><li><strong>Repassez ou vaporisez</strong> toutes les pièces, et prévoyez de quoi les retoucher sur place (épingles, ruban adhésif).</li><li>Prévoyez les <strong>bonnes tailles</strong> selon les modèles.</li><li>Rassemblez les <strong>accessoires</strong> (bijoux, sacs, ceintures) qui complètent chaque look.</li></ul>' },
      { h: 'Casting, coiffure et maquillage', html: '<p>Le choix du modèle, de la coiffure et du maquillage doit servir votre direction artistique : naturel pour l\'e-commerce, plus travaillé pour une campagne. Indiquez ces choix dans votre brief afin que tout le monde travaille dans la même direction.</p>' },
      { h: 'Le droit à l\'image', html: '<p>Avant le shooting, mettez par écrit ce qui a été convenu avec les modèles : <strong>usages autorisés</strong>, supports, durée et territoire, éventuelle rémunération. Cela protège la marque comme les modèles. En cas de doute, faites relire votre accord par un professionnel du droit.</p>' },
      { h: 'Construire une direction artistique', html: '<p>Rassemblez des références visuelles : ambiance, palette de couleurs, lumière, cadrages. Une fois votre devis confirmé, vous pouvez les structurer dans un <strong>moodboard</strong> depuis votre espace client, avec les produits ou pièces à présenter, et échanger avec l\'équipe par commentaires.</p>' },
      { h: 'Choisir la formule adaptée', html: '<p>Notre offre <a href="/services/photographe-mode-mannequins/" data-nav="service:mode">Mode, agences et mannequins</a> démarre à 490 € HT (Découverte, livraison en 5 jours ouvrés) et comprend aussi un abonnement mensuel réservé aux modèles et mannequins. Comparez le nombre de visuels, les tenues et les délais avant de demander un devis. Pour des photos brutes destinées à une agence, découvrez nos <a href="/conseils/polas-mannequin-digitals-agence/" data-nav="article:polas-mannequin-digitals-agence">Polas et digitals de mannequin</a>.</p>' },
      { h: 'Le déroulé type d\'une journée de shooting', html: '<p>En général, la journée commence par l\'<strong>installation</strong> (lumière, décor, portants), suivie d\'un <strong>look test</strong> pour valider la direction. Les tenues s\'enchaînent ensuite par séries, avec des <strong>pauses</strong> régulières pour le modèle et les changements de coiffure ou de maquillage. On termine par les détails (accessoires, plans serrés) et le rangement. Une bonne préparation permet de tout faire sans précipitation.</p>' },
      { h: 'Les erreurs fréquentes', html: '<ul><li><strong>Brief trop vague</strong> : sans références, chacun imagine un résultat différent.</li><li><strong>Pièces non repassées ou incomplètes</strong> : le temps de shooting se perd en préparation.</li><li><strong>Trop de looks pour le temps disponible</strong> : mieux vaut moins de tenues, mieux photographiées.</li><li><strong>Accord sur les droits flou</strong> : précisez par écrit les usages et la durée.</li></ul>' },
      { h: 'Retouche et cohérence de série', html: '<p>La retouche doit rester cohérente d\'un visuel à l\'autre : mêmes tons, même rendu de peau, mêmes proportions. Indiquez vos attentes (naturel, éditorial, très lissé ou non) dans le brief afin d\'éviter les allers-retours.</p>' },
    ],
    faq: [
      { q: 'Faut-il fournir les modèles ?', a: 'Précisez-le dans votre demande : le casting fait partie du brief et peut être organisé avec vous selon votre projet.' },
      { q: 'Comment recevoir des visuels homogènes pour une boutique ?', a: 'Fixez dès le départ le fond, le cadrage et la lumière, puis gardez-les identiques sur toute la série.' },
    ],
  },
  {
    slug: 'choisir-photographe-evenementiel',
    cat: 'event',
    title: 'Comment choisir son photographe d\'événement ? | BUNKAIO',
    description: 'Critères, questions à poser au prestataire et check-list de préparation pour choisir la bonne couverture photo de votre événement.',
    h1: 'Comment choisir son photographe d\'événement ?',
    excerpt: 'Critères de choix, questions à poser, déroulé et check-list : pour une couverture photo d\'événement sans mauvaise surprise.',
    date: '2026-10-02', minutes: 5,
    summary: ['Définissez les moments clés et l\'usage des photos (souvenirs, communication).', 'Comparez les portfolios sur des événements similaires au vôtre.', 'Vérifiez le devis : durée, délais, droits d\'utilisation, déplacement.', 'Transmettez un déroulé et une liste de personnes ou moments à ne pas manquer.', 'Prévenez les invités et les contraintes du lieu (lumière, accès).'],
    related: ['preparer-seance-photo-portrait', 'photobooth-mariage-bien-choisir'],
    sections: [
      { h: 'Définir vos besoins', html: '<p>Commencez par clarifier l\'objectif : <strong>souvenirs</strong> pour des invités, <strong>communication</strong> pour une entreprise, contenu pour les réseaux sociaux ? Notez la durée, le lieu, le nombre d\'invités et les moments à ne pas manquer (arrivée, discours, remises, cocktail, portraits de groupe).</p>' },
      { h: 'Les critères pour choisir', html: '<ul><li><strong>Le portfolio</strong> : cherchez des événements proches du vôtre (domaine, entreprise, réception).</li><li><strong>Le style</strong> : reportage discret, images posées, ambiance lumineuse ou plus contrastée.</li><li><strong>La discrétion et la réactivité</strong> : un bon photographe d\'événement se fait oublier tout en capturant l\'instant.</li><li><strong>Le cadre contractuel</strong> : durée de couverture, délais de livraison, droits d\'utilisation, frais de déplacement.</li><li><strong>La transparence du devis</strong> : ce qui est inclus, ce qui est optionnel.</li></ul>' },
      { h: 'Les questions à poser avant de réserver', html: '<ul><li>Quelle est la durée de couverture incluse et que se passe-t-il si l\'événement se prolonge ?</li><li>Combien de photos retouchées seront livrées, sous quel délai, sous quelle forme ?</li><li>Les droits d\'utilisation (usage commercial, durée) sont-ils précisés ?</li><li>Comment les photos sont-elles partagées (galerie privée, téléchargement) ?</li></ul>' },
      { h: 'Préparer l\'événement', html: '<p>Transmettez au photographe le <strong>déroulé</strong> (horaires, lieux, temps forts), la liste des personnes importantes et un <strong>contact sur place</strong>. Si possible, organisez un repérage du lieu pour anticiper la lumière, les accès et les contraintes. Informez les invités qu\'un photographe est présent.</p>' },
      { h: 'Chez BUNKAIO', html: '<p>Notre prestation <a href="/services/photographe-evenementiel/" data-nav="service:event">Événementiel</a> s\'adresse aux domaines, entreprises et réceptions, avec des formules dès 390 € HT et des photos retouchées livrées en 3 à 10 jours ouvrés selon la formule, dans une galerie privée. Pour un mariage, découvrez aussi <a href="/services/photobooth-ia-mariage-lumen/" data-nav="service:lumen">Lumen, notre photobooth IA</a>.</p>' },
      { h: 'Le déroulé idéal d\'une couverture', html: '<p>Avant l\'événement, le photographe arrive en avance pour <strong>repérer les lieux</strong> et la lumière. Pendant, il suit les moments clés de votre programme (accueil, discours, remises, cocktail) et prévoit un temps pour les <strong>portraits de groupe</strong>. Après, il trie et retouche les images avant de les livrer dans une galerie en ligne. Plus votre déroulé est précis, plus la couverture est complète.</p>' },
      { h: 'Les erreurs à éviter', html: '<ul><li><strong>Choisir uniquement sur le prix</strong> sans comparer ce qui est inclus.</li><li><strong>Ne pas transmettre le déroulé</strong> : le photographe découvre les temps forts au dernier moment.</li><li><strong>Oublier de prévenir un contact sur place</strong> pour les accès et les imprévus.</li><li><strong>Ne pas prévoir les portraits de groupe</strong> : ils demandent un moment dédié.</li></ul>' },
      { h: 'Le droit à l\'image des invités', html: '<p>Informez vos invités qu\'un photographe est présent. Si les photos servent à votre communication, assurez-vous que les personnes reconnaissables sont d\'accord pour cet usage, par exemple via un mot d\'information à l\'entrée ou une autorisation écrite.</p>' },
    ],
    faq: [
      { q: 'Combien de temps à l\'avance faut-il réserver ?', a: 'Le plus tôt possible : les créneaux sont limités chaque mois pour garantir la qualité de chaque prestation.' },
      { q: 'Les photos sont-elles utilisables pour la communication de mon entreprise ?', a: 'Oui : les droits d\'utilisation commerciale vous sont cédés sans limite de durée.' },
    ],
  },
  {
    slug: 'photobooth-mariage-bien-choisir',
    cat: 'lumen',
    title: 'Photobooth de mariage : comment bien le choisir | BUNKAIO',
    description: 'Durée, personnalisation, impressions, galerie en ligne : les critères et les questions pour choisir un photobooth de mariage ou d\'événement.',
    h1: 'Photobooth de mariage : comment bien le choisir',
    excerpt: 'Durée de présence, habillage, impressions, galerie en ligne : les points à vérifier avant de réserver un photobooth.',
    date: '2026-10-02', minutes: 4,
    summary: ['Fixez la durée de présence selon le déroulé de votre soirée.', 'Vérifiez la personnalisation : fond, habillage, palette.', 'Demandez si les impressions sont limitées ou illimitées.', 'Assurez-vous qu\'une galerie en ligne est fournie, et sous quel délai.', 'Anticipez l\'emplacement et l\'alimentation électrique avec le lieu.'],
    related: ['choisir-photographe-evenementiel', 'preparer-seance-photo-portrait'],
    sections: [
      { h: 'À quoi sert un photobooth de mariage ?', html: '<p>Au-delà de l\'animation, un photobooth offre à vos invités un souvenir immédiat et personnel, et aux mariés une collection d\'images spontanées de la soirée. Lumen, notre photobooth IA, génère un souvenir unique en quelques secondes, avec l\'élégance recherchée pour un mariage haut de gamme.</p>' },
      { h: 'Les critères à comparer', html: '<ul><li><strong>La durée de présence</strong> : alignez-la sur les moments où vos invités sont disponibles (cocktail, soirée).</li><li><strong>La personnalisation</strong> : fond, habillage, palette de couleurs en harmonie avec votre décoration.</li><li><strong>Les impressions</strong> : limitées ou illimitées ?</li><li><strong>La galerie en ligne</strong> : les photos vous sont-elles livrées, sous quel délai ?</li><li><strong>L\'installation</strong> : encombrement, électricité, temps de montage et de démontage.</li></ul>' },
      { h: 'Les formules Lumen', html: '<p>Lumen propose trois formules : <strong>Essentiel</strong> (550 € HT : photobooth installé, jusqu\'à 4 heures, impressions illimitées, galerie privée livrée sous 7 jours), <strong>Signature</strong> (1 100 € HT : jusqu\'à 6 heures, style personnalisé avec fond, habillage et palette, impressions illimitées, galerie privée sous 5 jours) et <strong>Sur-mesure</strong> sur devis. Le détail se trouve sur la page <a href="/services/photobooth-ia-mariage-lumen/" data-nav="service:lumen">Lumen</a>.</p>' },
      { h: 'Préparer le jour J avec votre lieu', html: '<ul><li>Demandez au lieu l\'emplacement possible et les contraintes d\'accès.</li><li>Confirmez la présence d\'une alimentation électrique à proximité.</li><li>Prévenez la personne qui coordonne la soirée (wedding planner, traiteur) de l\'horaire d\'installation.</li><li>Informez vos invités : une annonce ou un petit panneau suffit à lancer l\'animation.</li></ul>' },
      { h: 'Et si vous voulez aussi un photographe ?', html: '<p>Un photobooth complète un reportage photo, il ne le remplace pas. Pour couvrir votre événement, découvrez notre guide <a href="/conseils/choisir-photographe-evenementiel/" data-nav="article:choisir-photographe-evenementiel">Photographe événementiel : bien le choisir</a>.</p>' },
      { h: 'Combien de temps prévoir ?', html: '<p>Raisonnez à partir de votre programme : un photobooth est surtout utilisé pendant le cocktail et en début de soirée, puis de façon plus ponctuelle. Les formules Lumen couvrent jusqu\'à 4 heures (Essentiel) ou jusqu\'à 6 heures (Signature) : choisissez la durée qui correspond aux plages où vos invités sont réellement disponibles.</p>' },
      { h: 'Les erreurs à éviter', html: '<ul><li><strong>Réserver sans vérifier la personnalisation</strong> : un habillage cohérent avec votre décoration fait la différence.</li><li><strong>Oublier l\'emplacement</strong> : un coin trop discret ou trop bruyant freine l\'usage.</li><li><strong>Ignorer l\'alimentation électrique</strong> et l\'accès au lieu.</li><li><strong>Ne pas prévenir les invités</strong> : une annonce lance l\'animation.</li></ul>' },
      { h: 'Les questions à poser au prestataire', html: '<ul><li>Quelle est la durée de présence et la durée d\'installation ?</li><li>Quelles personnalisations sont possibles (fond, habillage, palette) ?</li><li>Les impressions sont-elles illimitées ?</li><li>Sous quel délai la galerie en ligne est-elle livrée ?</li><li>Que se passe-t-il en cas de problème technique pendant la soirée ?</li></ul>' },
    ],
    faq: [
      { q: 'Lumen convient-il uniquement aux mariages ?', a: 'Il est conçu en priorité pour les mariages, mais s\'adapte aussi aux réceptions privées, aux événements d\'entreprise et aux soirées organisées par des agences événementielles.' },
      { q: 'Les impressions sont-elles limitées ?', a: 'Sur les formules Essentiel et Signature, les impressions illimitées sont incluses.' },
    ],
  },
  {
    slug: 'polas-mannequin-digitals-agence',
    cat: 'mode',
    title: 'Polas et digitals de mannequin : à quoi ça sert | BUNKAIO',
    description: 'Polas (digitals) : des photos brutes pour agences de mannequins. Ce qu\'elles montrent, comment s\'y préparer et ce que comprend la formule BUNKAIO.',
    h1: 'Polas et digitals de mannequin : à quoi servent-elles ?',
    excerpt: 'Des photos brutes, sans retouche, destinées aux agences : ce qu\'elles montrent, comment s\'y préparer et ce que comprend notre formule Polas.',
    date: '2026-10-02', minutes: 4,
    summary: ['Les polas (ou digitals) sont des photos brutes, sans retouche ni mise en scène, destinées aux agences de mannequins.', 'Elles servent à évaluer la morphologie, la posture et le potentiel brut : visage, profils et plans en pied.', 'Chez BUNKAIO, la formule Polas se fait en studio sur fond blanc, avec une livraison HD sous 24 h.', 'Pour un book travaillé ou des visuels de marque, ce sont les formules Mode qui s\'appliquent.'],
    related: ['preparer-shooting-mode-lookbook', 'combien-coute-une-seance-photo'],
    sections: [
      { h: 'Qu\'est-ce que des polas (ou digitals) ?', html: '<p>Les polas, aussi appelées digitals, sont des photos <strong>brutes</strong> : sans retouche, sans mise en scène, sans effet. Elles sont destinées <strong>aux agences de mannequins</strong>, qui y cherchent une image fidèle de la personne telle qu\'elle est.</p>' },
      { h: 'Ce qu\'une agence cherche à y voir', html: '<p>Les polas permettent d\'évaluer la <strong>morphologie</strong>, la <strong>posture</strong> et le <strong>potentiel brut</strong> d\'un mannequin. Pour cela, la série comprend en général le visage, les profils et des plans en pied, sur fond neutre et sous une lumière simple.</p>' },
      { h: 'Se préparer à une séance de polas', html: '<ul><li><strong>Une tenue simple et près du corps</strong>, qui laisse voir la silhouette.</li><li><strong>Les cheveux dégagés</strong> et un visage naturel, avec peu ou pas de maquillage.</li><li><strong>Pas d\'accessoires</strong> ni de bijoux voyants.</li><li><strong>Les consignes de votre agence</strong> : elles peuvent varier d\'une agence à l\'autre, demandez-les avant la séance.</li></ul>' },
      { h: 'La formule Polas chez BUNKAIO', html: '<p>Notre formule Polas, proposée dans l\'offre <a href="/services/photographe-mode-mannequins/" data-nav="service:mode">Mode, agences et mannequins</a>, est facturée <strong>190 € HT</strong>, avec le <strong>studio obligatoire</strong> (60 € de supplément). Elle comprend :</p><ul><li>une séance studio sur fond blanc, en lumière neutre ;</li><li>des photos brutes, sans retouche ni mise en scène ;</li><li>le visage, les profils et des plans en pied ;</li><li>des fichiers HD prêts à transmettre à votre agence, livrés sous 24 h.</li></ul>' },
      { h: 'Polas ou book : quelle différence ?', html: '<p>Les polas sont un outil de présentation à destination des agences, pas un visuel de communication. Pour un <strong>book travaillé</strong>, un lookbook ou des visuels de marque, les formules Mode commencent à 490 € HT. Notre guide <a href="/conseils/preparer-shooting-mode-lookbook/" data-nav="article:preparer-shooting-mode-lookbook">Préparer un shooting mode</a> détaille la préparation.</p>' },
      { h: 'Obtenir un devis', html: '<p>La formule Polas se sélectionne dans le <a href="/devis/" data-nav="quiz">devis en ligne</a> de l\'univers Mode : estimation en 2 minutes, réponse personnalisée sous 48 h, sans engagement.</p>' },
    ],
    faq: [
      { q: 'Les polas sont-elles retouchées ?', a: 'Non : ce sont des photos brutes, sans retouche ni mise en scène.' },
      { q: 'Sous quel délai reçoit-on les polas ?', a: 'Les fichiers HD sont livrés sous 24 h.' },
      { q: 'Le studio est-il obligatoire ?', a: 'Oui : la séance Polas se fait en studio, sur fond blanc, avec un supplément de 60 €.' },
    ],
  },
  {
    slug: 'packshot-ou-mise-en-scene-photo-produit',
    cat: 'commercial',
    title: 'Packshot ou photo mise en scène : que choisir ? | BUNKAIO',
    description: 'Fond neutre ou produit mis en scène : quel style pour vos fiches produit, votre site et vos réseaux ? Critères de choix et formules BUNKAIO.',
    h1: 'Packshot ou photo de produit mise en scène : que choisir ?',
    excerpt: 'Fond neutre pour la fiche produit, mise en scène pour les réseaux : comment choisir selon l\'usage, et quelle formule retenir.',
    date: '2026-10-02', minutes: 4,
    summary: ['Le packshot isole le produit sur fond neutre : clair, fidèle, idéal pour les fiches produit.', 'La mise en scène place le produit dans une ambiance : elle sert surtout les réseaux et les pages de présentation.', 'Beaucoup de boutiques ont besoin des deux : un packshot par produit, quelques images d\'ambiance.', 'Chez BUNKAIO, la formule Découverte est en fond neutre ; la mise en scène est incluse dès Signature.'],
    related: ['preparer-shooting-photo-produit', 'combien-coute-une-seance-photo'],
    sections: [
      { h: 'Le packshot : le produit, rien que le produit', html: '<p>Un packshot présente le produit seul, sur un <strong>fond neutre</strong>, avec une lumière maîtrisée. Il montre fidèlement la forme, la matière et les couleurs. C\'est le format de référence pour une fiche produit : le visiteur voit exactement ce qu\'il achète.</p>' },
      { h: 'La mise en scène : le produit dans son univers', html: '<p>La photo mise en scène place le produit dans un décor, avec des accessoires, une lumière d\'ambiance et un parti pris visuel. Elle raconte un usage et une marque, et se prête aux <strong>réseaux sociaux</strong>, à la page d\'accueil ou aux supports de communication.</p>' },
      { h: 'Comment choisir selon l\'usage', html: '<ul><li><strong>Fiches produit et catalogue</strong> : packshot sur fond neutre. Vérifiez les règles de votre plateforme de vente, certaines imposent un type de fond.</li><li><strong>Réseaux sociaux et communication</strong> : mise en scène, pour donner une identité à votre marque.</li><li><strong>Lancement ou campagne</strong> : un mélange des deux, avec une série cohérente.</li></ul>' },
      { h: 'Ce que comprennent nos formules', html: '<p>Notre prestation <a href="/services/photo-produits-packshots/" data-nav="service:commercial">Commercial & produits</a> couvre les deux styles :</p><ul><li><strong>Découverte, 350 € HT</strong> : jusqu\'à 5 produits, 10 photos HD retouchées, fond neutre studio.</li><li><strong>Signature, 690 € HT</strong> : jusqu\'à 12 produits, 20 photos HD retouchées, mise en scène incluse.</li><li><strong>Premium, 1 290 € HT</strong> : jusqu\'à 25 produits, 35 photos HD retouchées, mise en scène incluse et 1 Reel vertical produit.</li><li><strong>Édition, 2 190 € HT</strong> : catalogue complet de 50 photos HD retouchées, 1 film de marque de 90 secondes et 2 Reels verticaux.</li></ul>' },
      { h: 'Bien préparer avant de choisir', html: '<p>Listez vos produits, l\'usage de chaque image (fiche, réseaux, publicité) et les formats attendus. Notre check-list <a href="/conseils/preparer-shooting-photo-produit/" data-nav="article:preparer-shooting-photo-produit">Préparer un shooting photo produit</a> vous guide pas à pas. Pour une estimation, utilisez le <a href="/devis/" data-nav="quiz">devis en ligne</a>.</p>' },
    ],
    faq: [
      { q: 'Quelle formule choisir pour des fiches produit ?', a: 'La formule Découverte propose des photos sur fond neutre studio, adaptées aux fiches produit : jusqu\'à 5 produits et 10 photos HD retouchées.' },
      { q: 'La mise en scène est-elle incluse ?', a: 'Oui, à partir de la formule Signature.' },
      { q: 'Les droits d\'utilisation sont-ils inclus ?', a: 'Oui : les droits d\'utilisation commerciale vous sont cédés sans limite de durée.' },
    ],
  },
  {
    slug: 'lieux-seance-photo-montpellier-beziers-toulouse',
    cat: 'photo-part',
    title: 'Lieux de séance photo à Montpellier, Béziers, Toulouse | BUNKAIO',
    description: 'Peyrou, canal du Midi, Pont-Neuf, Plateau des Poètes : des lieux photogéniques à Montpellier, Béziers et Toulouse, et comment choisir le vôtre.',
    h1: 'Où faire une séance photo à Montpellier, Béziers ou Toulouse ?',
    excerpt: 'Des lieux appréciés pour leur lumière et leur décor dans les trois villes où nous intervenons, et les critères pour choisir le bon.',
    date: '2026-10-02', minutes: 5,
    summary: ['Montpellier, Béziers et Toulouse offrent des décors très différents : pierre et jardins, canal et cathédrale, briques roses et quais.', 'Le meilleur lieu dépend de l\'ambiance recherchée, de la saison et de l\'heure : la lumière douce du matin ou de fin de journée est la plus flatteuse.', 'Certains lieux demandent une autorisation selon l\'usage des photos : nous vous conseillons au moment du devis.', 'BUNKAIO intervient dans ces trois villes, sans studio fixe : le lieu se choisit avec vous.'],
    related: ['preparer-seance-photo-portrait', 'que-porter-seance-photo'],
    sections: [
      { h: 'Comment choisir le lieu de sa séance', html: '<ul><li><strong>L\'ambiance voulue</strong> : architecture classique, nature, eau, lignes modernes.</li><li><strong>La lumière</strong> : en extérieur, le début de matinée et la fin d\'après-midi offrent une lumière douce.</li><li><strong>L\'affluence</strong> : un lieu très touristique est plus calme tôt le matin.</li><li><strong>La logistique</strong> : accès, stationnement, marche entre deux décors si la formule prévoit plusieurs lieux.</li></ul>' },
      { h: 'À Montpellier', html: '<ul><li><strong>La promenade du Peyrou</strong> : vaste esplanade avec son arc de triomphe, sa statue équestre de Louis XIV et son château d\'eau, pour des images élégantes et très architecturées.</li><li><strong>Le Jardin des Plantes</strong> : le plus ancien jardin botanique de France (1593), avec allées ombragées, serres et fontaines, pour un rendu naturel et apaisé.</li><li><strong>L\'Écusson</strong> : ruelles de la vieille ville, hôtels particuliers et façades de pierre, pour un décor urbain plein de caractère.</li><li><strong>Le quartier Antigone</strong> : l\'architecture néoclassique de Ricardo Bofill, ses lignes géométriques et ses perspectives, pour des portraits contemporains et stylisés.</li></ul>' },
      { h: 'À Béziers', html: '<ul><li><strong>Le canal du Midi et les neuf écluses de Fonséranes</strong> : un site emblématique du canal, pour des images où l\'eau et les ouvrages donnent du relief.</li><li><strong>La cathédrale Saint-Nazaire et le Pont Vieux</strong> : une vue sur la vallée de l\'Orb, et un reflet de la cathédrale dans l\'eau au petit matin.</li><li><strong>Le Plateau des Poètes</strong> : jardin en terrasses avec plan d\'eau, fontaine, statues et végétation variée.</li></ul>' },
      { h: 'À Toulouse', html: '<ul><li><strong>Le Pont-Neuf et les quais de la Garonne</strong> : arches en briques roses et lumière chaude en fin de journée.</li><li><strong>Le quai de la Daurade</strong> : un décor urbain sur les rives de la Garonne, avec vue sur le Pont-Neuf.</li><li><strong>Le Jardin des Plantes</strong> : jardin botanique de sept hectares près du canal du Midi, qui marie verdure et briques toulousaines.</li><li><strong>Le canal du Midi</strong> : classé à l\'UNESCO, avec berges arborées, écluses et ponts, particulièrement beau à l\'aube et au crépuscule.</li></ul>' },
      { h: 'Autorisations et usages', html: '<p>Les séances personnelles se déroulent généralement sans difficulté dans les lieux publics. Pour un usage commercial ou un projet plus important, certaines communes ou certains sites demandent une autorisation : indiquez l\'usage prévu dans votre demande et nous vous conseillons sur le lieu le plus adapté.</p>' },
      { h: 'Choisir sa formule', html: '<p>Une séance en extérieur peut se faire en un ou plusieurs lieux selon la formule : la formule Édition, par exemple, comprend une journée complète sur 4 lieux différents. Découvrez notre <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">séance photo particuliers</a>, ou lisez <a href="/conseils/preparer-seance-photo-portrait/" data-nav="article:preparer-seance-photo-portrait">comment préparer votre séance portrait</a>. Pour une estimation, passez par le <a href="/devis/" data-nav="quiz">devis en ligne</a>.</p>' },
    ],
    faq: [
      { q: 'Dans quelles villes intervenez-vous ?', a: 'À Béziers, Montpellier et Toulouse. Les déplacements sont offerts à Montpellier et à Béziers ; ils sont facturés à Toulouse et dans toute autre ville de France.' },
      { q: 'Peut-on choisir plusieurs lieux pendant la séance ?', a: 'Oui, selon la formule : la formule Édition prévoit une journée complète sur 4 lieux différents.' },
      { q: 'Faut-il une autorisation pour photographier dans un lieu public ?', a: 'Pour une séance personnelle, en général non ; pour un usage commercial, certains lieux en demandent une. Précisez l\'usage dans votre demande.' },
    ],
  },
  {
    slug: 'portrait-professionnel-photo-profil-linkedin',
    cat: 'corporate',
    title: 'Portrait professionnel : photo de profil, site, équipe | BUNKAIO',
    description: 'Photo de profil LinkedIn, site web, équipe : comment réussir son portrait professionnel, quoi porter et quelle formule choisir.',
    h1: 'Portrait professionnel : réussir sa photo de profil et de présentation',
    excerpt: 'Pour LinkedIn, votre site ou votre équipe : les clés d\'un portrait professionnel naturel, et la formule adaptée.',
    date: '2026-10-02', minutes: 4,
    summary: ['Un portrait professionnel sert à inspirer confiance : naturel, net, cohérent avec votre métier.', 'Prévoyez les usages (profil, site, presse, équipe) avant la séance : ils déterminent le cadrage et les formats.', 'Une tenue simple, confortable et sobre fonctionne mieux qu\'une tenue spécialement achetée.', 'Chez BUNKAIO, les séances portrait commencent à 230 € HT, avec des droits d\'utilisation commerciale cédés sans limite de durée.'],
    related: ['que-porter-seance-photo', 'lieux-seance-photo-montpellier-beziers-toulouse'],
    sections: [
      { h: 'À quoi sert un portrait professionnel ?', html: '<p>Votre portrait est souvent le premier contact avec vos clients ou recruteurs : profil LinkedIn, site web, présentation de l\'équipe, article de presse, signature de mail. Il doit refléter votre métier tout en restant naturel.</p>' },
      { h: 'Définir les usages avant la séance', html: '<ul><li><strong>Profil en ligne</strong> : cadrage serré sur le visage et les épaules.</li><li><strong>Site web</strong> : cadrage plus large, éventuellement avec un décor lié à votre activité.</li><li><strong>Équipe</strong> : un style homogène pour toutes les personnes, en séance individuelle ou en <a href="/services/seance-photo-particuliers/" data-nav="service:photo-part">groupe</a>.</li><li><strong>Presse et communication</strong> : formats horizontaux et verticaux.</li></ul>' },
      { h: 'Que porter ?', html: '<p>Choisissez une tenue sobre, confortable et proche de ce que vous portez au travail. Les couleurs unies fonctionnent bien ; évitez les motifs trop contrastés. Notre guide <a href="/conseils/que-porter-seance-photo/" data-nav="article:que-porter-seance-photo">Que porter pour une séance photo ?</a> détaille les couleurs et les matières.</p>' },
      { h: 'Extérieur ou studio ?', html: '<p>L\'extérieur donne un rendu vivant et lumineux ; le studio offre un fond maîtrisé et homogène, utile pour une équipe. Sur la formule Découverte, le studio est proposé avec un supplément de 60 €. Pour choisir un lieu, voir <a href="/conseils/lieux-seance-photo-montpellier-beziers-toulouse/" data-nav="article:lieux-seance-photo-montpellier-beziers-toulouse">nos idées de lieux à Montpellier, Béziers et Toulouse</a>.</p>' },
      { h: 'Quelle formule choisir ?', html: '<p>Pour un portrait professionnel, deux formules suffisent souvent : <strong>Découverte, 230 € HT</strong> (1 h de séance, 8 photos HD retouchées, sélection guidée, livraison en 5 jours ouvrés) ou <strong>Signature, 390 € HT</strong> (2 h de séance, 15 photos HD retouchées, direction de pose, livraison en 7 jours ouvrés). Les droits d\'utilisation commerciale vous sont cédés sans limite de durée. Retrouvez toutes les formules sur la page <a href="/services/portrait-professionnel-corporate/" data-nav="service:corporate">Corporate — portraits professionnels</a>.</p>' },
      { h: 'Obtenir une estimation', html: '<p>Le <a href="/devis/" data-nav="quiz">devis en ligne</a> prend 2 minutes : vous recevez une réponse personnalisée sous 48 h, sans engagement. Précisez que le portrait est destiné à un usage professionnel.</p>' },
    ],
    faq: [
      { q: 'Les photos sont-elles utilisables sur LinkedIn et sur mon site ?', a: 'Oui : les droits d\'utilisation commerciale vous sont cédés sans limite de durée.' },
      { q: 'Peut-on photographier toute une équipe ?', a: 'Oui : les séances sont possibles en solo, en couple ou en groupe, en extérieur ou en studio.' },
      { q: 'Dans quels délais reçoit-on les photos ?', a: 'Entre 5 et 10 jours ouvrés selon la formule choisie.' },
    ],
  },
];
