/* ═══════════════════════════════════════════════════════════
   ROUTES & MÉTADONNÉES SEO — config/routes.js
   Source unique lue par js/script.js (navigation, titre/description
   dynamiques) ET par tools/build-routes.mjs (pages HTML statiques,
   sitemap). Pour changer un titre ou une description : modifier ici,
   puis relancer `node tools/build-routes.mjs`.
   ═══════════════════════════════════════════════════════════ */
const SEO_ROUTES = [
  { view:'home', path:'/', index:true,
    title:'Photographe professionnel en Occitanie | BUNKAIO',
    description:'BUNKAIO, photographe professionnel mobile à Béziers, Montpellier et Toulouse : portrait, mode, produits, corporate, événementiel. Images haut de gamme en HD. Devis en 2 minutes.',
    titleEn:'Professional photographer in Occitanie | BUNKAIO',
    descriptionEn:'BUNKAIO, mobile professional photographer in Béziers, Montpellier and Toulouse: portrait, fashion, products, corporate, events. Premium HD images. Quote in 2 minutes.' },
  { view:'services', path:'/services/', index:true,
    title:'Prestations photo et tarifs | BUNKAIO, photographe Occitanie',
    description:'Séance photo particuliers, mode et mannequins, photo produits, corporate, événementiel, photobooth Lumen : formules et tarifs dès 230 €. Béziers, Montpellier, Toulouse. Photos livrées en HD.',
    titleEn:'Photography services and rates | BUNKAIO, Occitanie',
    descriptionEn:'Portrait sessions, fashion and models, product photography, events, Lumen photobooth: packages and rates from €230. HD delivery.' },
  { view:'service', cat:'photo-part', path:'/services/seance-photo-particuliers/', index:true,
    h1:'Séance photo portrait & lifestyle', h1En:'Portrait & lifestyle photo session',
    title:'Séance photo particuliers : portrait, couple, groupe | BUNKAIO',
    description:'Séance portrait et lifestyle en extérieur ou en studio, solo, couple ou groupe, à Béziers, Montpellier et Toulouse. Formules dès 230 €, photos retouchées en HD livrées en 5 à 10 jours ouvrés.',
    titleEn:'Portrait photo session: solo, couple, group | BUNKAIO',
    descriptionEn:'Portrait and lifestyle session outdoors or in studio, solo, couple or group, in Béziers, Montpellier and Toulouse. Packages from €230, retouched HD photos in 5 to 10 working days.' },
  { view:'service', cat:'mode', path:'/services/photographe-mode-mannequins/', index:true,
    h1:'Photographe mode, agences et mannequins', h1En:'Fashion, agency and model photographer',
    title:'Photographe mode, agences et mannequins : lookbook, e-commerce | BUNKAIO',
    description:'Photographie de mode pour marques, agences et mannequins : lookbooks et visuels e-commerce à Béziers, Montpellier et Toulouse. Formules dès 490 €, livraison en HD sous 5 à 10 jours ouvrés.',
    titleEn:'Fashion, agency and model photographer: lookbook, e-commerce | BUNKAIO',
    descriptionEn:'Fashion photography for brands, agencies and models: lookbooks and e-commerce visuals in Béziers, Montpellier and Toulouse. Packages from €490, HD delivery in 5 to 10 working days.' },
  { view:'service', cat:'commercial', path:'/services/photo-produits-packshots/', index:true,
    h1:'Photographie de produits et packshots', h1En:'Product photography and packshots',
    title:'Photo produit et packshots pour marques et entreprises | BUNKAIO',
    description:'Packshots et photographie de produits pour marques, artisans et entreprises à Béziers, Montpellier et Toulouse. Formules dès 350 €, livraison en HD sous 3 à 10 jours ouvrés.',
    titleEn:'Product photography and packshots for brands and businesses | BUNKAIO',
    descriptionEn:'Packshots and product photography for brands, artisans and businesses in Béziers, Montpellier and Toulouse. Packages from €350, HD delivery in 3 to 10 working days.' },
  { view:'service', cat:'event', path:'/services/photographe-evenementiel/', index:true,
    h1:'Photographe événementiel', h1En:'Event photographer',
    title:'Photographe événementiel : domaines, entreprises, réceptions | BUNKAIO',
    description:'Reportage photo d\'événements : domaines, entreprises, réceptions, à Béziers, Montpellier et Toulouse. Formules dès 390 €, photos retouchées livrées en 3 à 10 jours ouvrés.',
    titleEn:'Event photographer: estates, companies, receptions | BUNKAIO',
    descriptionEn:'Event photo coverage: estates, companies, receptions, in Béziers, Montpellier and Toulouse. Packages from €390, retouched photos delivered in 3 to 10 working days.' },
  { view:'service', cat:'lumen', path:'/services/photobooth-ia-mariage-lumen/', index:true,
    h1:'Lumen, le photobooth IA pour mariages et événements', h1En:'Lumen, the IA photobooth for weddings and events',
    title:'Lumen : photobooth IA pour mariages et événements | BUNKAIO',
    description:'Photobooth IA haut de gamme pour mariages et événements : installation, impressions illimitées, galerie privée. Formules dès 550 €. Béziers, Montpellier, Toulouse.',
    titleEn:'Lumen: IA photobooth for weddings and events | BUNKAIO',
    descriptionEn:'Premium IA photobooth for weddings and events: set-up, unlimited prints, private gallery. Packages from €550. Béziers, Montpellier, Toulouse.' },
  { view:'about', path:'/a-propos/', index:true,
    title:'À propos | Aya Nascimento, photographe portraitiste — BUNKAIO',
    description:'Aya Nascimento, photographe portraitiste professionnelle diplômée de l\'ETPA (BTS 2018) : mode, produit, corporate, événementiel. 8 ans d\'expérience, 200+ projets. Béziers, Montpellier, Toulouse.',
    titleEn:'About | Aya Nascimento, portrait photographer — BUNKAIO',
    descriptionEn:'Aya Nascimento, professional portrait photographer, ETPA graduate (BTS 2018): fashion, product, corporate, events. 8 years of experience, 200+ projects. Béziers, Montpellier, Toulouse.' },
  { view:'quiz', path:'/devis/', index:true,
    title:'Devis photo en ligne en 2 minutes | BUNKAIO',
    description:'Estimez votre séance photo en 2 minutes : choisissez votre univers, votre formule et vos options. Réponse personnalisée sous 48 h.',
    titleEn:'Online photo quote in 2 minutes | BUNKAIO',
    descriptionEn:'Estimate your photo session in 2 minutes: pick your universe, package and options. Personal reply within 48 hours.' },
  { view:'portfolio', path:'/portfolio/', index:true,
    title:'Portfolio photo : portrait, mode, produits, événements | BUNKAIO',
    description:'Découvrez les réalisations de BUNKAIO, photographe en Occitanie : portrait, mode, packshots produits, événementiel et mariage.',
    titleEn:'Photography portfolio: portrait, fashion, products, events | BUNKAIO',
    descriptionEn:'Discover the work of BUNKAIO, photographer in Occitanie: portrait, fashion, product packshots, events and weddings.' },
  { view:'contact', path:'/contact/', index:true,
    title:'Contact — Photographe en Occitanie | BUNKAIO',
    description:'Une question, un projet ? Écrivez à BUNKAIO, photographe mobile à Béziers, Montpellier et Toulouse. Réponse sous 24 h. Téléphone et email.',
    titleEn:'Contact — Photographer in Occitanie | BUNKAIO',
    descriptionEn:'A question, a project? Write to BUNKAIO, professional photographer in Occitanie. Reply within 24 hours. Phone and email.' },
  { view:'partners', path:'/partenaires/', index:true,
    title:'Partenariat et collaboration | BUNKAIO',
    description:'Devenez partenaire de BUNKAIO : tarif partenaire de -20 %, missions collaboratives rémunérées, réseau de professionnels. Candidatures ouvertes.',
    titleEn:'Partnership and collaboration | BUNKAIO',
    descriptionEn:'Become a BUNKAIO partner: 20% partner rate, paid collaborative missions, professional network. Applications open.' },
  { view:'legal', path:'/faq/', index:true,
    title:'FAQ : séance photo, paiement, annulation, droits | BUNKAIO',
    description:'Délais, paiement, droits d\'utilisation, annulation, espace client : toutes les réponses sur les séances photo BUNKAIO.',
    titleEn:'FAQ: photo sessions, payment, cancellation, rights | BUNKAIO',
    descriptionEn:'Delivery times, payment, usage rights, cancellation, client area: all the answers about BUNKAIO photo sessions.' },
  { view:'share', path:'/partager-mon-experience/', index:false,
    title:'Partager mon expérience | BUNKAIO',
    description:'Partagez votre retour d\'expérience avec BUNKAIO.',
    titleEn:'Share my experience | BUNKAIO', descriptionEn:'Share your feedback with BUNKAIO.' },
  { view:'drone', path:'/drone/', index:false,
    title:'4K Drone — bientôt disponible | BUNKAIO',
    description:'La rubrique 4K Drone de BUNKAIO sera bientôt disponible.',
    titleEn:'4K Drone — coming soon | BUNKAIO', descriptionEn:'BUNKAIO 4K Drone is coming soon.' },
  { view:'login', path:'/connexion/', index:false,
    title:'Connexion à votre espace | BUNKAIO',
    description:'Accédez à votre espace client ou partenaire BUNKAIO.',
    titleEn:'Sign in to your space | BUNKAIO', descriptionEn:'Access your BUNKAIO client or partner area.' },
  { view:'account', path:'/espace-client/', index:false,
    title:'Mon espace | BUNKAIO',
    description:'Votre espace client ou partenaire BUNKAIO.',
    titleEn:'My space | BUNKAIO', descriptionEn:'Your BUNKAIO client or partner area.' },
];
