/* ═══════════════════════════════════════════════════════════
   ROUTES & MÉTADONNÉES SEO — config/routes.js
   Source unique lue par js/script.js (navigation, titre/description
   dynamiques) ET par tools/build-routes.mjs (pages HTML statiques,
   sitemap). Pour changer un titre ou une description : modifier ici,
   puis relancer `node tools/build-routes.mjs`.
   ═══════════════════════════════════════════════════════════ */
const SEO_ROUTES = [
  { view:'home', path:'/', index:true,
    title:'BUNKAIO ⊹ | Photographe à Montpellier, Béziers et Toulouse',
    description:'BUNKAIO, photographe professionnel basé à Montpellier, mobile à Béziers et Toulouse : portrait, mode, produit, événementiel. Images HD haut de gamme.',
    titleEn:'BUNKAIO ⊹ | Professional photographer in Occitanie',
    descriptionEn:'BUNKAIO, mobile professional photographer in Béziers, Montpellier and Toulouse: portrait, fashion, products, corporate, events. Premium HD images. Quote in 2 minutes.' },
  { view:'services', path:'/services/', index:true,
    title:'BUNKAIO ⊹ | Prestations photo et tarifs, photographe Occitanie',
    description:'Séance photo, mode et mannequins, photo produit, événementiel, photobooth Lumen : formules et tarifs dès 230 €. Béziers, Montpellier, Toulouse.',
    titleEn:'BUNKAIO ⊹ | Photography services and rates, Occitanie',
    descriptionEn:'Portrait sessions, fashion and models, product photography, events, Lumen photobooth: packages and rates from €230. HD delivery.' },
  { view:'service', cat:'photo-part', path:'/services/seance-photo-particuliers/', index:true,
    h1:'Séance photo portrait & lifestyle', h1En:'Portrait & lifestyle photo session',
    title:'BUNKAIO ⊹ | Séance photo portrait à Montpellier, Béziers, Toulouse',
    description:'Séance portrait et lifestyle en extérieur ou en studio, solo, couple ou groupe. Béziers, Montpellier, Toulouse. Dès 230 €, photos HD en 5 à 10 jours.',
    titleEn:'BUNKAIO ⊹ | Portrait photo session: solo, couple, group',
    descriptionEn:'Portrait and lifestyle session outdoors or in studio, solo, couple or group, in Béziers, Montpellier and Toulouse. Packages from €230, retouched HD photos in 5 to 10 working days.' },
  { view:'service', cat:'corporate', path:'/services/portrait-professionnel-corporate/', index:true,
    h1:'Portrait professionnel et photo corporate', h1En:'Professional portrait and corporate photography',
    title:'BUNKAIO ⊹ | Portrait professionnel à Montpellier, Béziers, Toulouse',
    description:'Portraits professionnels pour dirigeants, indépendants et équipes : LinkedIn, site web. Montpellier, Béziers, Toulouse. Dès 230 €, HD en 5 à 10 jours.',
    titleEn:'BUNKAIO ⊹ | Professional portraits in Montpellier, Béziers, Toulouse',
    descriptionEn:'Professional portraits for executives, freelancers and teams: LinkedIn, website. Montpellier, Béziers, Toulouse. Packages from €230, HD delivery in 5 to 10 working days.' },
  { view:'service', cat:'mode', path:'/services/photographe-mode-mannequins/', index:true,
    h1:'Photographe mode, agences et mannequins', h1En:'Fashion, agency and model photographer',
    title:'BUNKAIO ⊹ | Photographe mode et mannequins à Montpellier',
    description:'Photographie de mode pour marques, agences et mannequins : lookbooks et e-commerce. Béziers, Montpellier, Toulouse. Dès 490 €, HD en 5 à 10 jours.',
    titleEn:'BUNKAIO ⊹ | Fashion, agency and model photographer: lookbook, e-commerce',
    descriptionEn:'Fashion photography for brands, agencies and models: lookbooks and e-commerce visuals in Béziers, Montpellier and Toulouse. Packages from €490, HD delivery in 5 to 10 working days.' },
  { view:'service', cat:'commercial', path:'/services/photo-produits-packshots/', index:true,
    h1:'Photographie de produits et packshots', h1En:'Product photography and packshots',
    title:'BUNKAIO ⊹ | Photo produit et packshots à Montpellier, Béziers, Toulouse',
    description:'Packshots et photographie de produits pour marques, artisans et entreprises. Béziers, Montpellier, Toulouse. Dès 350 €, HD en 3 à 10 jours ouvrés.',
    titleEn:'BUNKAIO ⊹ | Product photography and packshots for brands and businesses',
    descriptionEn:'Packshots and product photography for brands, artisans and businesses in Béziers, Montpellier and Toulouse. Packages from €350, HD delivery in 3 to 10 working days.' },
  { view:'service', cat:'event', path:'/services/photographe-evenementiel/', index:true,
    h1:'Photographe événementiel', h1En:'Event photographer',
    title:'BUNKAIO ⊹ | Photographe événementiel à Montpellier, Béziers, Toulouse',
    description:'Reportage photo d\'événements : domaines, entreprises, réceptions. Béziers, Montpellier, Toulouse. Dès 390 €, photos retouchées en 3 à 10 jours.',
    titleEn:'BUNKAIO ⊹ | Event photographer: estates, companies, receptions',
    descriptionEn:'Event photo coverage: estates, companies, receptions, in Béziers, Montpellier and Toulouse. Packages from €390, retouched photos delivered in 3 to 10 working days.' },
  { view:'service', cat:'lumen', path:'/services/photobooth-ia-mariage-lumen/', index:true,
    h1:'Lumen, le photobooth IA pour mariages et événements', h1En:'Lumen, the AI photobooth for weddings and events',
    title:'BUNKAIO ⊹ | Lumen : photobooth IA pour mariages et événements',
    description:'Photobooth IA haut de gamme pour mariages et événements : impressions illimitées, galerie privée. Dès 550 €. Béziers, Montpellier, Toulouse.',
    titleEn:'BUNKAIO ⊹ | Lumen: AI photobooth for weddings and events',
    descriptionEn:'Premium AI photobooth for weddings and events: set-up, unlimited prints, private gallery. Packages from €550. Béziers, Montpellier, Toulouse.' },
  { view:'discover', path:'/decouvrir-chaque-prestation/', index:true,
    h1:'Découvrir chaque prestation', h1En:'Explore each service',
    title:'BUNKAIO ⊹ | Découvrir chaque prestation photo à Montpellier',
    description:'Portrait, corporate, mode, produit, événementiel, Lumen : trouvez la prestation photo adaptée à votre besoin, à Montpellier, Béziers, Toulouse. Dès 230 €.',
    titleEn:'BUNKAIO ⊹ | Explore each photography service in Montpellier',
    descriptionEn:'Portrait, corporate, fashion, product, events, Lumen: find the photography service that fits your need, in Montpellier, Béziers, Toulouse. From €230.' },
  { view:'about', path:'/a-propos/', index:true,
    title:'À propos | Aya Nascimento, photographe portraitiste — BUNKAIO',
    description:'Aya Nascimento, photographe portraitiste diplômée de l\'ETPA (BTS 2018) : mode, produit, corporate, événementiel. 8 ans d\'expérience, 200+ projets.',
    titleEn:'About | Aya Nascimento, portrait photographer — BUNKAIO',
    descriptionEn:'Aya Nascimento, professional portrait photographer, ETPA graduate (BTS 2018): fashion, product, corporate, events. 8 years of experience, 200+ projects. Béziers, Montpellier, Toulouse.' },
  { view:'quiz', path:'/devis/', index:true,
    title:'BUNKAIO ⊹ | Devis photo en ligne en 2 minutes',
    description:'Estimez votre séance photo en 2 minutes : choisissez votre univers, votre formule et vos options. Réponse personnalisée sous 48 h.',
    titleEn:'BUNKAIO ⊹ | Online photo quote in 2 minutes',
    descriptionEn:'Estimate your photo session in 2 minutes: pick your universe, package and options. Personal reply within 48 hours.' },
  { view:'portfolio', path:'/portfolio/', index:true,
    title:'BUNKAIO ⊹ | Portfolio photo : portrait, mode, produits, événements',
    description:'Découvrez les réalisations de BUNKAIO, photographe en Occitanie : portrait, mode, packshots produits, événementiel et mariage.',
    titleEn:'BUNKAIO ⊹ | Photography portfolio: portrait, fashion, products, events',
    descriptionEn:'Discover the work of BUNKAIO, photographer in Occitanie: portrait, fashion, product packshots, events and weddings.' },
  { view:'contact', path:'/contact/', index:true,
    title:'BUNKAIO ⊹ | Contact — Photographe à Montpellier',
    description:'Une question, un projet ? Écrivez à BUNKAIO, photographe basé à Montpellier et mobile à Béziers et Toulouse. Réponse sous 24 h. Téléphone et email.',
    titleEn:'BUNKAIO ⊹ | Contact — Photographer in Occitanie',
    descriptionEn:'A question, a project? Write to BUNKAIO, professional photographer in Occitanie. Reply within 24 hours. Phone and email.' },
  { view:'partners', path:'/collaboration/', index:true,
    title:'BUNKAIO ⊹ | Collaboration et partenariat photo',
    description:'Devenez partenaire de BUNKAIO : tarif partenaire de -20 %, missions collaboratives rémunérées, réseau de professionnels. Candidatures ouvertes.',
    titleEn:'BUNKAIO ⊹ | Collaboration and partnership',
    descriptionEn:'Become a BUNKAIO partner: 20% partner rate, paid collaborative missions, professional network. Applications open.' },
  { view:'legal', path:'/faq/', index:true,
    title:'BUNKAIO ⊹ | FAQ : séance photo, paiement, annulation, droits',
    description:'Délais, paiement, droits d\'utilisation, annulation, espace client : toutes les réponses sur les séances photo BUNKAIO.',
    titleEn:'BUNKAIO ⊹ | FAQ: photo sessions, payment, cancellation, rights',
    descriptionEn:'Delivery times, payment, usage rights, cancellation, client area: all the answers about BUNKAIO photo sessions.' },
  { view:'legal', sub:'privacy', path:'/confidentialite/', index:false,
    h1:'Politique de confidentialité et mentions légales',
    title:'BUNKAIO ⊹ | Politique de confidentialité et mentions légales',
    description:'Données personnelles, mesure d\'audience sans cookie, droits d\'auteur et mentions légales de BUNKAIO.',
    titleEn:'BUNKAIO ⊹ | Privacy policy and legal notice',
    descriptionEn:'Personal data, cookie-free audience measurement, copyright and legal notice of BUNKAIO.' },
  { view:'share', path:'/partager-mon-experience/', index:false,
    title:'BUNKAIO ⊹ | Partager mon expérience',
    description:'Partagez votre retour d\'expérience avec BUNKAIO.',
    titleEn:'BUNKAIO ⊹ | Share my experience', descriptionEn:'Share your feedback with BUNKAIO.' },
  { view:'drone', path:'/drone/', index:false,
    title:'BUNKAIO ⊹ | 4K Drone — bientôt disponible',
    description:'La rubrique 4K Drone de BUNKAIO sera bientôt disponible.',
    titleEn:'BUNKAIO ⊹ | 4K Drone — coming soon', descriptionEn:'BUNKAIO 4K Drone is coming soon.' },
  { view:'login', path:'/connexion/', index:false,
    title:'BUNKAIO ⊹ | Connexion à votre espace',
    description:'Accédez à votre espace client ou partenaire BUNKAIO.',
    titleEn:'BUNKAIO ⊹ | Sign in to your space', descriptionEn:'Access your BUNKAIO client or partner area.' },
  { view:'account', path:'/espace-client/', index:false,
    title:'BUNKAIO ⊹ | Mon espace',
    description:'Votre espace client ou partenaire BUNKAIO.',
    titleEn:'BUNKAIO ⊹ | My space', descriptionEn:'Your BUNKAIO client or partner area.' },
];

/* Pages de conseils : le hub et un article par entrée de ARTICLES (config/articles.js). */
if (typeof ARTICLES !== 'undefined') {
  SEO_ROUTES.push({ view:'advice', path:'/conseils/', index:true,
    title:'BUNKAIO ⊹ | Conseils photo : séance, shooting, événement',
    description:'Guides pratiques d\'une photographe professionnelle : préparer une séance portrait, choisir ses tenues, organiser un shooting produit, mode ou événement.',
    titleEn:'BUNKAIO ⊹ | Photo advice: prepare your session, shoot or event',
    descriptionEn:'Practical guides from a professional photographer: preparing a portrait session, choosing outfits, planning a product, fashion or event shoot.' });
  ARTICLES.forEach(a => SEO_ROUTES.push({ view:'article', slug:a.slug, path:'/conseils/' + a.slug + '/', index:true,
    title:a.title, description:a.description, h1:a.h1,
    titleEn:(typeof ARTICLES_EN !== 'undefined' && ARTICLES_EN[a.slug]) ? ARTICLES_EN[a.slug].title : a.title,
    descriptionEn:(typeof ARTICLES_EN !== 'undefined' && ARTICLES_EN[a.slug]) ? ARTICLES_EN[a.slug].description : a.description,
    h1En:(typeof ARTICLES_EN !== 'undefined' && ARTICLES_EN[a.slug]) ? ARTICLES_EN[a.slug].h1 : a.h1 }));
}
